<a href="https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/capstone_exp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Capstone experiment — mirrors your deployed research paper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/capstone.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [4]:
from pathlib import Path
import os

print("Current directory:", os.getcwd())

for root in [Path.cwd(), Path("/content"), Path("/content/drive/MyDrive")]:
    if root.exists():
        print(f"\n--- {root} ---")
        for p in root.glob("**/capstone.ipynb"):
            if ".ipynb_checkpoints" not in str(p):
                print(p)

Current directory: /content

--- /content ---

--- /content ---

In [5]:
import os
import subprocess
from pathlib import Path

print("Git version:")
subprocess.run(["git", "--version"], check=False)

print("\nFolders in /content:")
for item in Path("/content").iterdir():
    print(item)

Git version:

Folders in /content:
/content/.config
/content/sample_data

In [6]:
!git clone https://github.com/ch-jsk/jsk-flyrank-ml-internship.git

Cloning into 'jsk-flyrank-ml-internship'...
remote: Enumerating objects: 162, done.
remote: Counting objects: 100% (162/162), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 162 (delta 68), reused 92 (delta 28), pack-reused 0 (from 0)
Receiving objects: 100% (162/162), 1.88 MiB | 7.47 MiB/s, done.
Resolving deltas: 100% (68/68), done.

In [7]:
from pathlib import Path

repo = Path("/content/jsk-flyrank-ml-internship")

for path in [
    repo / "skills" / "README.md",
    repo / "work" / "notebooks" / "capstone.ipynb",
]:
    print(f"{'FOUND' if path.exists() else 'NOT FOUND'}: {path}")

FOUND: /content/jsk-flyrank-ml-internship/skills/README.md
FOUND: /content/jsk-flyrank-ml-internship/work/notebooks/capstone.ipynb

In [8]:
from pathlib import Path

repo = Path("/content/jsk-flyrank-ml-internship")

readme = repo / "skills" / "README.md"
print(readme.read_text(encoding="utf-8"))

# Skills — the router

This folder is a small library of **skills**: focused instruction files your AI assistant loads
one at a time. One skill per task keeps the assistant sharp — its context window is small, and
filling it with everything makes it worse at the one thing you need.

**How to use it (repo-reading agents — Claude Code, Cursor, Codex):** they find this file
automatically via `AGENTS.md` / `CLAUDE.md`. Just tell your assistant which task you're doing.

**Using a chat-only assistant (ChatGPT / Gemini in a browser)?** Open the skill file on GitHub,
copy its whole content, and paste it into your chat before asking for help. That's it.

## The table — find your task, load ONE skill

| Your task | Load this skill | Also load for data work |
|---|---|---|
| Any task — how to work with your assistant at all | `directing-your-ai-assistant/SKILL.md` | — |
| Pick a lane, frame your question (ML-02, ML-03) | `framing-ml-problems/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Write + verify the data contract (ML-04) | `writing-data-contracts/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Query the big warehouse without downloading it (ML-04/05, capstone) | `querying-big-datasets/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| EDA + signal tests with verdicts (ML-06) | `auditing-signals/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Build the rule baseline + ranked queue (ML-07) | `building-baselines/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Train and compare the model (ML-08) | `training-honest-models/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Hunt leakage; validate honestly (ML-05, ML-09) | `hunting-leakage-and-validating/SKILL.md` | `flyrank/flyrank-data/SKILL.md` |
| Write claims that hold (ML-09, ML-10, the paper) | `writing-honest-claims/SKILL.md` | — |
| Write the research paper (ML-11, W7) | `writing-research-papers/SKILL.md` | — |
| Deploy the paper as a page (ML-11) | `deploying-static-pages/SKILL.md` | — |
| Understand FlyRank + the problem (background) | `flyrank/flyrank-context/SKILL.md` | — |

## Reuse this on your next project

Every skill outside `flyrank/` is **general** — take this whole folder to any future project.
Delete `skills/flyrank/` and the flyrank column above, and everything else still works.

In [9]:
from pathlib import Path

repo = Path("/content/jsk-flyrank-ml-internship")

skill_files = [
    repo / "skills" / "directing-your-ai-assistant" / "SKILL.md",
    repo / "skills" / "querying-big-datasets" / "SKILL.md",
    repo / "skills" / "flyrank" / "flyrank-data" / "SKILL.md",
]

for path in skill_files:
    print("\n" + "=" * 80)
    print(f"FILE: {path.relative_to(repo)}")
    print("=" * 80)

    if path.exists():
        print(path.read_text(encoding="utf-8"))
    else:
        print("NOT FOUND")

================================================================================
FILE: skills/directing-your-ai-assistant/SKILL.md
================================================================================
---
name: directing-your-ai-assistant
description: Teaches the working method for using an AI coding assistant on analysis tasks — one task per fresh conversation, search before assuming, interview before big plans, validate everything, commit per finished task. Use at the start of any assignment, whenever a conversation gets long and confused, or when the assistant starts guessing.
---

# Directing your AI assistant

You are the engineer. The assistant is a fast, tireless drafter. This skill is how you stay in
charge — because an assistant with a confused human produces confused work, fast.

## The six rules

**1. One task, one fresh conversation.** An assistant's memory (its "context window") fills up
and its quality drops as it fills. So: finish one assignment section per conversation, then start
a new one. Never drag one giant chat across a whole week — old confusion bleeds into new work.

**2. Load only what the task needs.** Point it at the router (`skills/README.md`), load the one
skill for this task, and stop. More instructions ≠ better output — past a point, more is worse.

**3. Search before assuming.** Before the assistant writes anything, make it look: "Search this
repo first — don't assume something is missing or not implemented." Assistants invent functions
and columns when they haven't looked. Anchoring them in real files kills most hallucinations.

**4. Interview before big plans.** For anything bigger than one cell, say: "Before you write
code, interview me — ask the questions you need answered." Wrong assumptions caught in questions
cost seconds; caught in finished code they cost hours. Do not outsource the thinking.

**5. You validate — always.** The assistant drafts; you check. Every task ends the same way:
run the notebook top to bottom (Runtime → Run all), read the output, and ask "does this actually
answer my question?" An unverified answer is not an answer. Checks are your safety rail: the more
things that can automatically reject bad output (a rerun, an assertion, CI), the safer you move.

**6. Commit each finished task.** When a section works, commit it with a message that says what
and why. Small commits = easy recovery when something later goes wrong.

## Prompts that work (copy these)

- "Read `skills/README.md`, then load `<skill>` for this task."
- "Search the repo first — don't assume it's not implemented. Then propose a plan before coding."
- "Interview me before writing this: what do you need to know?"
- "Write this cell, then tell me exactly how I verify it worked."
- "Here is the error output, unedited: <paste>. Fix the actual cause, not the symptom."

Paste real errors whole — don't summarize them. The assistant fixes what it can see.

## How to verify you're using this skill right

- Your conversations are short and single-purpose; you can name each one's task in five words.
- The assistant asked you at least one clarifying question before any multi-step work.
- Every finished section ran top to bottom before you committed it.
- You can explain, in your own words, everything you committed. If you can't — that's the signal
  to slow down: core idea first, AI second.


================================================================================
FILE: skills/querying-big-datasets/SKILL.md
================================================================================
---
name: querying-big-datasets
description: Works with datasets far too big to download or load in pandas — SQL over remote Parquet with DuckDB, aggregate-then-model, iterate on samples. Use when a dataset has millions of rows, lives on a remote host (hf:// or s3), or a notebook runs out of memory or hits rate limits.
---

# Querying big datasets

The trick that makes 79 million rows feel small: **never bring the rows to you — send the
question to the rows.** Aggregate in SQL, bring back only the small answer, model on that.

## The pattern

```python
%pip -q install duckdb
import duckdb
con = duckdb.connect()
# remote Parquet reads like a local table — match the path to how the table ships:
# most tables are ONE flat file at the repo root:
REL = "read_parquet('hf://datasets/<org>/<name>/<table>.parquet')"
# partitioned tables are a directory of month folders:
REL = "read_parquet('hf://datasets/<org>/<name>/<table>/month=2026-03/*.parquet')"
# several months: pass an explicit LIST of paths — hf:// does NOT support {brace} globs,
# and pointing the /**/ glob at a flat-file table fails with an opaque HTTP error.
small = con.sql(f"""
    SELECT group_col, SUM(metric) AS total, COUNT(*) AS n
    FROM {REL}
    WHERE date_col >= DATE '2026-01-01'
    GROUP BY group_col
""").df()          # <- pandas gets ONLY the aggregate
```

- `COUNT(*)` and `MIN/MAX(date)` over Parquet touch metadata, not data — they're near-free.
  Start every session with them to confirm you're pointed at the right thing.
- Filter + aggregate in SQL; join small results in pandas; fit sklearn on the small frame.
- For gated remote data, register the token once:
  `con.execute("CREATE OR REPLACE SECRET hf (TYPE huggingface, TOKEN '<token>')")` — and never
  paste a token into a cell in a public repo; use getpass or the notebook's secrets panel.

## Iterate on the sample, finish on the full table

Remote hosts rate-limit repeated heavy scans (you'll see HTTP 429). So:

1. **Develop your query on the sample table** (if the release ships one) or on one month/partition.
2. Get the logic right there — cheap, fast, repeatable.
3. **Run the full scan once**, when the query is final. Cache the result to a local file
   (`df.to_parquet('work/outputs/features.parquet')`) so reruns don't re-scan.

If you get 429 anyway: stop, wait a minute, and switch to the sample. Hammering makes it worse.

## Grain guards (the classic big-table mistake)

In detail tables, per-item context columns repeat on every row. `SUM()` on them double-counts.
Use `ANY_VALUE(context_col)` (or group first at the right grain) — and test the grain with a
`GROUP BY ... HAVING COUNT(*) > 1` probe before trusting any aggregate.

## How to verify

- Your notebook reruns end-to-end in minutes, not hours — because heavy scans happen once and
  cache locally.
- Row counts from your aggregates reconcile with the dataset's published counts.
- No cell holds a raw multi-million-row dataframe. If one does, push that work into SQL.


================================================================================
FILE: skills/flyrank/flyrank-data/SKILL.md
================================================================================
---
name: flyrank-data
description: The FlyRank internship datasets — the 30k-row starter CSV and its gotchas, the ~79M-row warehouse release tables and grains, panel warnings, access, and iteration rules. Load for EVERY task that touches the data. (Project-specific: delete this folder when reusing the skill library elsewhere.)
---

# FlyRank internship data

Two datasets. The small one ships in this repo; the big one is hosted and gated.

## 1. Starter dataset (in this repo)

`data/raw/content_refresh_anonymized.csv` — 30,000 rows × 44 columns, one row per pseudonymized
content item, 32 clients, trailing-90-day metrics. Full column reference: `docs/data-dictionary.md`
(keep it open). The gotchas that cause 90% of mistakes:

- **Rate columns are ×100 percentages**: `ctr = 0.76` means 0.76%, not 76%. Applies to ctr,
  engagement_rate, scroll_rate, ai_traffic_pct, trend_pct.
- **`avg_position = 0` means "no data"**, not rank zero (1,205 rows).
- **`scroll_rate` and `ai_traffic_pct` can exceed 100** — numerator and denominator come from
  different measurement systems. Not a bug; read the dictionary.
- **The label trap:** `is_declining_label` is derived from `trend_direction`, which is computed
  from `trend_pct`. Therefore `trend_direction` and `trend_pct` are NEVER features.
- **Missingness follows content_type** (one type has ~100% missing keyword data; another ~28%
  missing word_count) — a blind fillna(0) injects a category signal. Add has_-flags instead.
- **IDs (`content_id`, `client_id`) are pseudonyms:** grouping/joining/splitting only, never
  features. Use client_id for grouped train/test splits.

## 2. Warehouse release (Hugging Face, gated — instant approval)

`hf://datasets/FlyRank/internship-warehouse` — build v20260703:

| Table | Rows | Grain |
|---|---|---|
| `dim_clients` | 104 | one per pseudonymized client |
| `dim_content` | 519,606 | one per content item |
| `fact_content_daily_performance` | 78,835,655 | report_date × client × content (partitioned by month) |
| `fact_content_daily_performance_sample` | ~11.7M | same grain — the FINAL MONTH (June 2026) only; fine for query mechanics, NEVER for label logic |
| `fact_content_query_90d` | 2,414,248 | client × content × query hash, fixed 90-day window |

Dates: 2025-01-27 → 2026-06-30 (~17 months). Position column is `gsc_avg_position`.

**Panel warnings (they are real):**
- History depth differs wildly per client — check `dim_clients.gsc_data_start` before defining
  any time window; prefer per-client windows over one global calendar window.
- Rows before a client's `ga4_data_start` have GA4 columns zero-FILLED with
  `ga4_data_available = FALSE` — filter on the flag; zeros there are not "no engagement".
- A third of clients have little or no usable search/analytics history — expect to filter.
- The query table's per-content context columns repeat on every row: `ANY_VALUE()` them, never
  `SUM()`. Its 90-day window overlaps the snapshot's final months — if your label lives in the
  last 30 days, only `*_prev30`-style columns are safe features (window alignment first!).

**Access + iteration rules:** request gate access once (instant), READ token via Colab
Secrets (`HF_TOKEN`) or env var — never pasted in a cell (public repo!). Iterate on a
**mid-panel month partition** (e.g. `month=2026-03`), not the `_sample`: the `_sample` is the
panel's LAST month, i.e. the natural outcome window of any past→future label — develop label
logic there and you are developing inside your own test window. Treat the final month as a
sealed test month. Run the full 79M scan ONCE when the query is final and cache the result to
`work/outputs/`. Repeated full scans hit HTTP 429 rate limits.

## How to verify

- Start any session with `COUNT(*)` + `MIN/MAX(report_date)` on your table and match the
  numbers above.
- Grain-probe before aggregating: `GROUP BY <grain cols> HAVING COUNT(*) > 1 LIMIT 5` → empty.
- If a number looks absurd (a 400% rate, a giant ratio from 12 rows), re-read the gotchas
  before celebrating.

In [10]:
from pathlib import Path
import json

repo = Path("/content/jsk-flyrank-ml-internship")
notebook_path = repo / "work" / "notebooks" / "capstone.ipynb"

# 1. Inspect existing notebook cells
with notebook_path.open(encoding="utf-8") as f:
    notebook = json.load(f)

print("NOTEBOOK:", notebook_path)
print("TOTAL CELLS:", len(notebook["cells"]))

for i, cell in enumerate(notebook["cells"]):
    source = "".join(cell.get("source", []))
    preview = source[:700].strip()
    print(f"\n--- Cell {i} | {cell['cell_type']} ---")
    print(preview if preview else "[Empty cell]")

# 2. Find relevant project files without opening large datasets
print("\n\n--- RELEVANT PROJECT FILES ---")
for folder in ["data", "docs", "submission", "work", "skills"]:
    root = repo / folder
    if root.exists():
        print(f"\n[{folder}]")
        count = 0
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            if any(part.startswith(".") for part in path.parts):
                continue
            if path.suffix.lower() in {
                ".csv", ".md", ".py", ".sql", ".json",
                ".yml", ".yaml", ".txt", ".ipynb"
            }:
                print(path.relative_to(repo))
                count += 1
                if count >= 35:
                    print("... listing capped at 35 files")
                    break

NOTEBOOK: /content/jsk-flyrank-ml-internship/work/notebooks/capstone.ipynb
TOTAL CELLS: 16

--- Cell 0 | markdown ---
# Capstone — mirrors your deployed research paper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/capstone.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

--- Cell 1 | markdown ---
## 1. Question

*The research question and the decision it supports.*

--- Cell 2 | code ---
[Empty cell]

--- Cell 3 | markdown ---
## 2. Data

*Which release, which tables, date windows, what you excluded and why. Public-safe.*

--- Cell 4 | code ---
[Empty cell]

--- Cell 5 | markdown ---
## 3. Methodology

*Assumptions, features, label definition, baseline, validation design, leakage checks.*

--- Cell 6 | code ---
[Empty cell]

--- Cell 7 | markdown ---
## 4. Results (vs baseline)

*Model vs baseline on the same split. The honest table.*

--- Cell 8 | code ---
[Empty cell]

--- Cell 9 | markdown ---
## 5. Limitations

*What this work cannot claim.*

--- Cell 10 | code ---
[Empty cell]

--- Cell 11 | markdown ---
## 6. Ranked recommendations

*The action playbook output — the paper's recommendations section.*

--- Cell 12 | code ---
[Empty cell]

--- Cell 13 | markdown ---
## 7. Artifacts the paper embeds

*Generate/collect the charts and tables your deployed page will show.*

--- Cell 14 | code ---
[Empty cell]

--- Cell 15 | markdown ---
## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.
- [ ] My deployed paper has **all 9 sections** — including the **Abstract** at the top and **Acknowledgments & data credit** (the https://flyrank.ai link) at the bottom.
- [ ] **ML-12 done in this notebook's closing cells:** 5-minute demo ou


--- RELEVANT PROJECT FILES ---

[data]
data/raw/content_refresh_anonymized.csv

[docs]
docs/data-dictionary.md
docs/ml-core-foundation-framework.md
docs/ml-intern-dataset-and-lane-guide.md
docs/intern-free-tooling-guide.md

[submission]
submission/paper_url.txt
submission/README.md

[work]
work/README.md
work/capstone_report_template.md
work/notebooks/w04_baseline_score.ipynb
work/notebooks/w05_model.ipynb
work/notebooks/w07_action_playbook.ipynb
work/notebooks/w04_signal_audit.ipynb
work/notebooks/w03_feature_leakage_check.ipynb
work/notebooks/w03_data_contract.ipynb
work/notebooks/w06_validation_audit.ipynb
work/notebooks/capstone.ipynb
work/notebooks/w02_ml_task_framing.ipynb
work/notebooks/w01_research_question.ipynb

[skills]
skills/README.md
skills/writing-data-contracts/SKILL.md
skills/training-honest-models/SKILL.md
skills/writing-research-papers/SKILL.md
skills/writing-honest-claims/SKILL.md
skills/building-baselines/SKILL.md
skills/hunting-leakage-and-validating/SKILL.md
skills/directing-your-ai-assistant/SKILL.md
skills/framing-ml-problems/SKILL.md
skills/deploying-static-pages/SKILL.md
skills/auditing-signals/SKILL.md
skills/querying-big-datasets/SKILL.md
skills/flyrank/flyrank-data/SKILL.md
skills/flyrank/flyrank-context/SKILL.md

In [11]:
from pathlib import Path
import json

repo = Path("/content/jsk-flyrank-ml-internship")

notebooks = [
    "work/notebooks/w01_research_question.ipynb",
    "work/notebooks/w02_ml_task_framing.ipynb",
    "work/notebooks/w03_data_contract.ipynb",
    "work/notebooks/w03_feature_leakage_check.ipynb",
    "work/notebooks/w04_signal_audit.ipynb",
    "work/notebooks/w04_baseline_score.ipynb",
    "work/notebooks/w05_model.ipynb",
    "work/notebooks/w06_validation_audit.ipynb",
    "work/notebooks/w07_action_playbook.ipynb",
]

for relative_path in notebooks:
    path = repo / relative_path
    print("\n" + "=" * 90)
    print("NOTEBOOK:", relative_path)

    if not path.exists():
        print("NOT FOUND")
        continue

    with path.open(encoding="utf-8") as f:
        nb = json.load(f)

    for i, cell in enumerate(nb.get("cells", [])):
        source = "".join(cell.get("source", []))
        if cell["cell_type"] == "markdown":
            if source.strip().startswith("#"):
                print(f"\n[Markdown {i}]\n{source[:350]}")
        elif source.strip():
            print(f"\n[Code {i}]\n{source[:1000]}")
            outputs = cell.get("outputs", [])
            for output in outputs:
                text_out = "".join(output.get("text", []))
                if text_out.strip():
                    print("[Saved output]", text_out[:700])
                for item in output.get("data", {}).get("text/plain", [])[:1]:
                    print("[Saved result]", str(item)[:500])

==========================================================================================
NOTEBOOK: work/notebooks/w01_research_question.ipynb

[Markdown 1]
# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has

[Markdown 2]
## 1. My lane (or freestyle) and why

I chose **Lane 4: CTR / Engagement Opportunity Scoring**.

My goal is to identify webpages that receive good search visibility but appear to underperform in click-through rate (CTR) or engagement compared to similar pages. Instead of comparing all pages directly, I want to compare pages within similar search-po

[Code 3]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 4]
## 2. The question: decision, action, cost of a wrong call

**Research question :** Which webpages appear to underperform in CTR compared with other pages in the same search-position tier, and should therefore be prioritised for review?

**Unit of analysis :** One webpage (one content item).

**Decision :** Which pages should the SEO or content tea

[Code 5]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 6]
## 3. Quick look at the data (2-3 real numbers)

*Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.*

[Code 7]
!git clone https://github.com/ch-jsk/jsk-flyrank-ml-internship.git
[Saved output] Cloning into 'jsk-flyrank-ml-internship'...
remote: Enumerating objects: 127, done.
remote: Counting ob

[Code 8]
%cd jsk-flyrank-ml-internship
[Saved output] /content/jsk-flyrank-ml-internship/jsk-flyrank-ml-internship


[Code 9]
!ls
[Saved output] AGENTS.md  DATA_USE.md	LICENSE    README.md	     SETUP.md	 work
CLAUDE.md  docs		notebooks  requirements.txt  skills
data	   GUIDE.md	outputs    scripts	     submission


[Code 10]
# This cell is for CODE (numbers, a query, a check).

import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))
print(df["ctr"].describe())
print(df["avg_position"].describe())
print(df["content_type"].value_counts())
[Saved output] Rows: 30000
Columns: 44
count    30000.000000
mean         0.510733
std          3.279162
min          0.000000
25%          0.000000
50%          0.070000
75%          0.290000
max        100.000000
Name: ctr, dtype: float64
count    30000.00000
mean        16.34238
std         15.21679
min          0.00000
25%          6.20000
50%         10.80000
75%         22.30000
max        245.00000
Name: avg_position, dtype: float64
content_type
keyword article       27207
feedly article         2096
comparison article      697
Name: count, dtype: int64


[Markdown 12]
## 4. Careful words: what I can and can't claim

This project will identify pages that appear to underperform relative to similar-position pages based on the available data. The findings are observational and intended to support decision-making.

This work cannot prove that changing a title, metadata, or content will increase CTR or improve Google

[Code 13]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 14]
## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decisi

==========================================================================================
NOTEBOOK: work/notebooks/w02_ml_task_framing.ipynb

[Markdown 0]
# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line

[Markdown 1]
## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

I chose **Lane 4: CTR / Engagement Opportunity Scoring**.

This is primarily a **ranking / scoring** problem rather than a classification problem. The goal is not simply to predict whether a page is "good" or "bad," but to assign each webpag

[Code 2]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 3]
## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*


The project does not have a directly observed label that says whether a page deserves optimisation. Instead, I will use a proxy based on the gap between a page's actual CTR and the expected CTR for pages within the same search-po

[Code 4]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 5]
## 3. Success metric

*One metric you can defend. What number means 'good'?*

Because this is a ranking problem, success will be measured by how effectively the system prioritises useful optimisation opportunities.

One suitable metric is **Precision@K**, which measures how many of the top-ranked recommendations are genuinely worthwhile for review.

[Code 6]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 7]
## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

Each row represents **one webpage (one content item)**.

Each row contains information such as impressions, clicks, CTR, average position, content type, freshness, and engagement metrics that describe the performance of that page.

[Code 8]
import os

print(os.getcwd())
[Saved output] /content/jsk-flyrank-ml-internship


[Code 9]
!git clone https://github.com/ch-jsk/jsk-flyrank-ml-internship.git
[Saved output] Cloning into 'jsk-flyrank-ml-internship'...
remote: Enumerating objects: 132, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 132 (delta 45), reused 92 (delta 28), pack-reused 0 (from 0)
Receiving objects: 100% (132/132), 1.85 MiB | 6.16 MiB/s, done.
Resolving deltas: 100% (45/45), done.


[Code 10]
%cd jsk-flyrank-ml-internship
[Saved output] /content/jsk-flyrank-ml-internship/jsk-flyrank-ml-internship


[Code 11]
!ls data/raw
[Saved output] content_refresh_anonymized.csv


[Code 12]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

print(df.shape)

df.head()

[Saved output] (30000, 44)

[Saved result]              content_id          client_id  search_volume  competition  \


[Code 13]
df[["ctr", "avg_position"]].head()
[Saved result]     ctr  avg_position


[Markdown 15]
## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

A simple rule such as "review every page with CTR below 1%" would ignore important context like search position, impressions, freshness, content type, and engagement.

Pages naturally receive different CTRs depending on where they rank in search results.

[Code 16]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 17]
## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decisi

==========================================================================================
NOTEBOOK: work/notebooks/w03_data_contract.ipynb

[Markdown 1]
# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-li

[Markdown 2]
## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

**Unit of analysis**

One row represents the performance of one content item for one client on one reporting date.

**Tables used**

- dim_content
- fact_content_daily_performance

**Time window**

I will work with a mid-panel month (March

[Code 3]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

print("Lane:", "CTR / Engagement Opportunity Scoring")
print("Month:", "2026-03")
[Saved output] Lane: CTR / Engagement Opportunity Scoring
Month: 2026-03


[Markdown 4]
## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

**Features**
- impressions
- clicks
- ctr
- gsc_avg_position
- content_age_days

**Label or proxy**
- expected CTR gap
- optimisation priority score

**Context fields**
- report_date
- client_id
- content_id

**Ex

[Code 5]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

features = [
    "impressions",
    "clicks",
    "ctr",
    "gsc_avg_position",
    "content_age_days",
]

excluded = [
    "trend_direction",
    "trend_pct",
    "is_declining_label",
]

print("Features")
print(features)

print("\nExcluded")
print(excluded)

[Saved output] Features
['impressions', 'clicks', 'ctr', 'gsc_avg_position', 'content_age_days']

Excluded
['trend_direction', 'trend_pct', 'is_declining_label']


[Markdown 6]
## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

The following checks verify the grain of the data, the available date range, and the presence of missing values.

[Code 7]
!pip install -q datasets huggingface_hub pyarrow pandas

[Code 8]
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

print(HF_TOKEN[:1])
[Saved output] h


[Code 9]
from huggingface_hub import login

login(token=HF_TOKEN)

[Code 10]
from datasets import load_dataset

dim_content = load_dataset(
    "FlyRank/internship-warehouse",
    "dim_content",
    token=HF_TOKEN
)

[Code 11]
print(dim_content)
[Saved output] DatasetDict({
    train: Dataset({
        features: ['client_hash_id', 'content_hash_id', 'keyword_hash_id', 'url_hash_id', 'keyword_char_count', 'keyword_token_count', 'url_char_count', 'content_created_date', 'content_updated_date', 'content_type', 'search_volume', 'competition', 'competition_level', 'cpc', 'main_intent', 'backlinks', 'category_count', 'keyword_created_date', 'provider_used', 'model_used', 'char_count', 'word_count', 'last_optimized_date', 'optimization_eligible_date', 'is_published', 'is_deleted'],
        num_rows: 519606
    })
})


[Code 12]
df = dim_content["train"].to_pandas()

print(df.shape)
df.head()
[Saved output] (519606, 26)

[Saved result]             client_hash_id           content_hash_id  \


[Code 13]
#Verify the grain
print("Rows:", len(df))
print("Unique content IDs:", df["content_hash_id"].nunique())
[Saved output] Rows: 519606
Unique content IDs: 519606


[Code 14]
#Verify the date span
date_cols = [col for col in df.columns if "date" in col.lower()]
print(date_cols)
[Saved output] ['content_created_date', 'content_updated_date', 'keyword_created_date', 'last_optimized_date', 'optimization_eligible_date']


[Code 15]
for col in date_cols:
    print("\n", col)

    values = df[col].dropna()

    print("Minimum:", values.min())
    print("Maximum:", values.max())
[Saved output]
 content_created_date
Minimum: 2024-10-16
Maximum: 2026-07-06

 content_updated_date
Minimum: 2024-10-28
Maximum: 2026-07-06

 keyword_created_date
Minimum: 2024-10-16
Maximum: 2026-07-02

 last_optimized_date
Minimum: 2026-04-24
Maximum: 2026-07-06

 optimization_eligible_date
Minimum: 2026-06-08
Maximum: 2026-08-20


[Code 16]
#Verify missing values
missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

print(missing.head(10))
[Saved output] optimization_eligible_date    474210
last_optimized_date           474210
provider_used                 369936
backlinks                     267474
word_count                    177768
char_count                    177768
main_intent                   148398
competition_level             144456
cpc                           142622
search_volume                 142622
dtype: int64


[Code 17]
#See all available columns
print(df.columns.tolist())
[Saved output] ['client_hash_id', 'content_hash_id', 'keyword_hash_id', 'url_hash_id', 'keyword_char_count', 'keyword_token_count', 'url_char_count', 'content_created_date', 'content_updated_date', 'content_type', 'search_volume', 'competition', 'competition_level', 'cpc', 'main_intent', 'backlinks', 'category_count', 'keyword_created_date', 'provider_used', 'model_used', 'char_count', 'word_count', 'last_optimized_date', 'optimization_eligible_date', 'is_published', 'is_deleted']


[Markdown 18]
### Verification results

The following checks were performed to verify the contract.

- The number of unique content identifiers matches the number of rows.
- The content table spans from late 2024 to mid-2026.
- Missing values were identified and examined before feature selection.
- The structure of the data was inspected to ensure that the selec

[Markdown 19]
## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

- Historical depth differs across clients.
- Some columns contain large numbers of missing values.
- Search position strongly affects CTR.
- Metadata alone cannot fully explain user behaviour.
- Observed patterns should be treated as d

[Code 20]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 21]
## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decisi

==========================================================================================
NOTEBOOK: work/notebooks/w03_feature_leakage_check.ipynb

[Markdown 0]
# ML-05 — Feature Vector and Leakage/Privacy Check

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/w03_feature_leakage_check.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each o

[Markdown 1]
## 1. Build the feature vector

*Code that actually builds it — engineered features, categorical handling, fills.*

[Code 2]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 3]
## 2. Feature notes (meaning, missing, categorical, available-when?)

*For each feature: what it means, how missing values are handled, and whether it exists BEFORE the moment you predict.*

[Code 4]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 5]
## 3. The leakage hunt

*Attack your own features: label-derived columns, future windows, product flags. Show the test.*

[Code 6]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 7]
## 4. What I excluded and why

*The list of fields you refused to use — with one line of why each.*

[Code 8]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 9]
## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decisi

==========================================================================================
NOTEBOOK: work/notebooks/w04_signal_audit.ipynb

[Markdown 0]
# ML-06 — Signal Audit: Do the Flags Hold?

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/w04_signal_audit.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line

[Markdown 1]
## 1. Distributions

*Look before deciding: distributions of your key fields. Note the heavy tails.*

[Code 2]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 3]
## 2. Signal test #1 / #2 / #3 (verdict each)

*Three safe signals, each with a mini-test and a verdict: CONFIRMED / OPPOSITE / MIXED / FALSE.*

[Code 4]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 5]
## 3. The flag-linked test

*Pick a signal one of FlyRank's real flags relies on. Does the data support the rule's assumption?*

[Code 6]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 7]
## 4. What this means in practice

*Two or three sentences: what a content team should take from this.*

[Code 8]
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


[Markdown 9]
## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decisi

==========================================================================================
NOTEBOOK: work/notebooks/w04_baseline_score.ipynb

[Markdown 0]
# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)


In [12]:
from pathlib import Path

repo = Path("/content/jsk-flyrank-ml-internship")

files_to_inspect = [
    "DATA_USE.md",
    "docs/ml-intern-dataset-and-lane-guide.md",
    "docs/data-dictionary.md",
    "work/README.md",
    "work/capstone_report_template.md",
]

for relative_path in files_to_inspect:
    path = repo / relative_path
    print("\n" + "=" * 75)
    print(f"FILE: {relative_path}")
    print("=" * 75)

    if path.exists():
        lines = path.read_text(encoding="utf-8").splitlines()
        print("\n".join(lines[:100]))
        if len(lines) > 100:
            print(f"\n... ({len(lines) - 100} more lines)")
    else:
        print("NOT FOUND")

print("\n" + "=" * 75)
print("EXISTING OUTPUTS AND SCRIPTS")
print("=" * 75)

for folder_name in ["work/outputs", "work/figures", "scripts"]:
    folder = repo / folder_name
    print(f"\n[{folder_name}]")
    if folder.exists():
        for path in sorted(folder.iterdir()):
            print(path.name)
    else:
        print("Folder does not exist")

===========================================================================
FILE: DATA_USE.md
===========================================================================
# Data Use & Public-Safety Rules

The one dataset that ships with this repo is:

```text
data/raw/content_refresh_anonymized.csv
```

It is a small, **anonymized** slice of FlyRank content-performance data — one row per
pseudonymized content item, with observed search/engagement metrics, content metadata,
age/freshness fields, and derived comparison windows.

## What has already been removed

The starter export contains **no**:

- client names
- domains
- URLs
- page titles
- keywords or raw search queries
- product-rule flags used as composite scores you should trust blindly

Only hashed `content_id` / `client_id` labels plus numeric and categorical metrics remain.

Rate columns (`ctr`, `engagement_rate`, `scroll_rate`, `ai_traffic_pct`, `trend_pct`) are
percentages on a 0–100 scale: `ctr = 0.76` means 0.76%, not 76%.

The hashed IDs are pseudonyms derived from FlyRank-internal database identifiers. They
contain no public information, but treat them as pseudonymous, not anonymous: use them
for grouping and joining only, never as model features, and never attempt to map them back.

## Your rules while working

1. **Do not add raw private client data** to this repo or any fork of it. If you need
   more data than the starter slice, request an approved release from your mentor —
   never export it yourself.
2. **Do not paste this data (or any client data) into third-party tools** — cloud AI
   assistants, free APIs, hosted notebooks — beyond what the approved release allows.
   Treat every external tool as third-party processing.
3. **Hashed IDs are for grouping/joining/validation only** — use them for grouped
   train/test splits, not as model features.
4. **Observable signals only.** The starter data ships observable search/engagement
   metrics and transparent derived buckets. FlyRank's product decision flags and scores
   (`health_score`, `needs_ctr_fix`, `is_quick_win`, …) are intentionally not included,
   so you build from observable evidence and never learn the product's own decision.
5. **Public outputs must use careful language** — *observed, measured, directional,
   decision-support*. Never claim you "predicted Google's algorithm" or proved causal
   refresh impact. Publish aggregates, charts, and pseudonymized IDs — never careless
   row-level dumps.

## When you publish your capstone

Your final repo is public. Before you push:

- confirm no raw client identifiers, URLs, or queries appear anywhere;
- confirm you did not commit a larger dataset than the anonymized starter slice;
- keep claims honest and decision-support framed.

CI fails any commit that includes a dataset or leaks client-identifying
patterns — this rule doubles as the public-safety discipline the internship teaches.

===========================================================================
FILE: docs/ml-intern-dataset-and-lane-guide.md
===========================================================================
# FlyRank ML Internship - Your Dataset and Lane Guide

Status: your guide for the Applied Search Intelligence track.

Read this together with:

- `docs/ml-core-foundation-framework.md` (ships in this repo — a deep reference, not week-one reading)
- `docs/intern-free-tooling-guide.md` (ships in this repo)
- the week-by-week curriculum on your portal board
- the data dictionary and manifest that ship inside the dataset release on Hugging Face

> This starter repo ships only the small anonymized starter dataset (`data/raw/content_refresh_anonymized.csv`).
> The much larger warehouse release lives on Hugging Face at
> [`FlyRank/internship-warehouse`](https://huggingface.co/datasets/FlyRank/internship-warehouse).
> It is gated, which means you click "request access" and accept the data-use terms first —
> approval is instant, so you can get it yourself whenever your lane needs it.

This guide shows you how to use the data without turning the internship into a fill-in-the-blank exercise. The goal is not to memorize FlyRank's existing rules. The goal is to understand the problem, look at the evidence, build a simple starting point, test a better method, check it honestly, and turn the result into a ranked list of safe recommendations.

## 0. Where These Numbers Come From

Every count and date in this guide was checked against the real data pipeline, not written from memory. The release itself was built, scrambled, and verified on FlyRank's side before it was published; the details of that build live in the dataset manifest that ships with the release on Hugging Face. You don't need any of that tooling — everything you need is already in this repo and on Hugging Face:

- the runnable starter pipeline (`scripts/01`–`05`, `ml_utils.py`, `run_all.py`);
- its verified committed outputs (`outputs/model_report.md`, `outputs/refresh_queue_sample.csv`, `outputs/charts/`); `outputs/model_results.json` is regenerated when you run the pipeline;
- the small anonymized starter dataset (`data/raw/content_refresh_anonymized.csv`).

One important rule about snapshots (a snapshot is a copy of the data frozen at one moment in time):

- For warehouse work, use the Hugging Face release. It is a fixed snapshot with the exact date windows written out below.
- Stick to this release for your internship work — it is the snapshot every number in this guide describes, so results built on it can be compared and rerun.
- You never need raw BigQuery credentials, raw client names, raw domains, raw URLs, raw private queries, or raw text. Everything sensitive was removed or scrambled before release.

## 1. The Core Idea

The whole track follows one workflow:

```text
research question -> safe data contract -> signal audit -> baseline score -> your chosen lane -> validation -> ranked action recommendations
```

Here is what those words mean, in order. A **research question** is the one question your project answers. A **data contract** is a short written promise about which data you will use and how. A **signal audit** is a check of whether the columns actually contain useful information. A **baseline** is the simplest possible method, built first, so you have something honest to beat. **Validation** is the test that proves your result is real and not an accident. **Ranked action recommendations** are the final output: a list of pages, ordered by which one someone should look at first.

The teaching method is:

```text
core idea first -> AI-assisted implementation second -> human judgment last
```

That means:

- Start with the content and search problem, not with a model.
- Use AI to draft code, ideas, checks, and explanations — but never let AI decide what is true. You check that yourself, against the data.
- Treat product scores and flags as useful background, not as the truth.
- Prefer simple methods you can explain, until something harder is clearly worth it.
- Tie every claim you make to something the data can actually prove.

Your deliverables along the way are notebooks, and they already have homes: pre-named skeleton notebooks live in `work/notebooks/` (for example `w01_research_question.ipynb` through `w07_action_playbook.ipynb`, plus `capstone.ipynb`). You fill those in — you do not create separate report files.

## 2. Which Data To Use

Your internship data is the warehouse release described below, plus the small runnable starter dataset that ships in this repo. Both contain **observable signals only** — real measurements of what happened, never the product's own decisions.

### About the Release

The warehouse release, and how to get it:

- Release: [`FlyRank/internship-warehouse`](https://huggingface.co/datasets/FlyRank/internship-warehouse) on Hugging Face. It is gated — request access, accept the data-use terms, and approval is instant. Notebook 03 shows the DuckDB workflow for reading it. Build id: `flyrank_pseudonymized_warehouse_release_v20260703`.
- Source: `central_data_warehouse`
- Export date: `2026-07-03`
- Freshness lag: the freshest 3 days were cut off on purpose, because the very newest rows are often incomplete — 3 days back from `2026-07-03` means daily time-series facts stop at `2026-06-30`
- Chunk size: 10,000 rows per CSV part
- How it was scrambled and verified: identifiers were pseudonymized (replaced with stable scrambled codes) and the release passed its checks before publishing — the full details are in the dataset manifest on Hugging Face.

> **Building features and iterating?** Develop against one middle month (e.g. `month=2026-03`) and run the full fact table only for your final pass — hitting the full table over and over can trip Hugging Face rate limits (HTTP 429 errors). Avoid the `_sample` table for experiments: it holds the LAST month of data, and if your label is about "what happens next", experimenting there means peeking at the future you're supposed to predict.

When you write about the data, use only the counts and date windows below — they match the release exactly.

### Which Lanes Are Ready, and With What Data

A **lane** is a project direction you can pick. Four lanes are predefined, and freestyle means bringing your own question (section 9 explains it).

| Lane | Type | Default dataset | Output |
|---|---|---|---|
| Ranking Signal Analysis | Core lane | warehouse release or starter dataset | Signal report and evidence-backed recommendations |
| Refresh / Content Opportunity Scoring | Core lane | starter playground plus warehouse support | Ranked review queue with scores, actions, and reason codes |
| Structured Content Archetype Clustering | Core lane | warehouse release or starter dataset | Cluster profiles and action mapping; do not call this semantic clustering |
| CTR / Engagement Opportunity Scoring | Core lane | warehouse release or starter dataset | Ranked opportunity score; position/volume adjusted |
| AI Referral Opportunity | Freestyle direction | warehouse daily facts (`sessions_ai`; starter dataset: `ai_sessions_90d` / `ai_traffic_pct`) | EDA/ranking only by default; positive examples are sparse |
| Growth / Recovery / Momentum Prediction | Freestyle direction | warehouse daily facts with time windows you build yourself | Future-window model with strict leakage audit |

### The Warehouse Tables

The warehouse release gives you **dimension tables** and **fact tables**. A dimension table describes things (one row per client, one row per content item). A fact table records events over time (one row per content item per day). You define your own joins, windows, labels, and leakage checks — that freedom is the point.

The release is hosted at
[`FlyRank/internship-warehouse`](https://huggingface.co/datasets/FlyRank/internship-warehouse)
(gated; Parquet files; see notebook 03). Ready-made example cuts for each lane live at
[`FlyRank/internship-lanes`](https://huggingface.co/datasets/FlyRank/internship-lanes). Build id:


... (628 more lines)

===========================================================================
FILE: docs/data-dictionary.md
===========================================================================
# Data Dictionary — `content_refresh_anonymized.csv`

One row per content item (page): **30,000 rows × 44 columns**, covering **32 pseudonymized
clients**. All metrics are aggregated over a trailing 90-day window ending at export time.
Keep this file open while you work.

## Read this first — the three rules that prevent 90% of mistakes

1. **Rate columns are ×100 percentages.** `ctr = 0.76` means **0.76%**, not 76%. Applies to
   `ctr`, `engagement_rate`, `scroll_rate`, `ai_traffic_pct`, `trend_pct`.
2. **The label comes from `trend_direction`.** The pipeline defines
   `is_declining_label = (trend_direction == "down")`, so `trend_direction` and `trend_pct`
   must **never** be model features — that's the leakage notebook 02 demonstrates.
3. **IDs are for grouping only.** `content_id` / `client_id` are pseudonyms: use them for
   joins and grouped train/test splits, never as features.

## Identifiers

| Column | Type | Meaning | Notes |
|---|---|---|---|
| `content_id` | text | Pseudonymous page id (`content_` + 12 hex chars) | Unique per row. Grouping/joins only |
| `client_id` | text | Pseudonymous client id (`client_` + 10 hex chars) | 32 distinct values. Use for **client-holdout splits** |

> **Missingness is systematic, not random.** Keyword-context columns are missing along
> `content_type` lines (e.g. `feedly article` rows have no keyword data at all). A blind
> `fillna(0)` therefore encodes content type into your features silently — check missingness
> per content_type before imputing.

## Keyword context (from content metadata)

| Column | Type | Meaning | Notes |
|---|---|---|---|
| `search_volume` | number | Search-volume estimate for the page's target keyword | 0–74,000 in this slice; blank for 2,468 rows with no keyword data |
| `competition` | number | Keyword competition score, 0–1 | Blank when no keyword data |
| `competition_level` | category | `LOW` / `MEDIUM` / `HIGH` | Blank when no keyword data |
| `cpc` | number | Cost-per-click estimate for the target keyword | Blank when no keyword data |
| `content_type` | category | `keyword article` / `feedly article` / `comparison article` | |
| `main_intent` | category | `informational` / `transactional` / `commercial` / `navigational` | Blank when unknown |

## Content properties

| Column | Type | Meaning | Notes |
|---|---|---|---|
| `word_count` | number | Article word count | Blank for 7,699 rows (not measured) |
| `char_count` | number | Article character count | Blank alongside `word_count` |
| `provider_used` | category | LLM provider that generated the article: `openai` / `google` / `other` | Blank when unknown. Not a model feature |
| `model_used` | category | LLM model name (e.g. `gemini-2.5-flash`, `gpt-4o-mini`) | Blank/`unknown` when not recorded. Not a model feature |
| `content_age_days` | number | Days since the content was created | Every row in this slice is ≥ 90 |
| `days_since_last_update` | number | Days since the content was last updated | |

## 90-day activity totals (GSC = Google Search Console, GA4 = Google Analytics)

| Column | Type | Meaning |
|---|---|---|
| `impressions_90d` | number | GSC search impressions (every row in this slice has ≥ 1) |
| `clicks_90d` | number | GSC clicks from search results |
| `pageviews_90d` | number | GA4 pageviews |
| `sessions_90d` | number | GA4 sessions |
| `users_90d` | number | GA4 users |
| `engaged_sessions_90d` | number | GA4 engaged sessions |
| `ai_sessions_90d` | number | GA4 sessions referred from AI tools — **click-throughs from AI assistants, not citations or rankings** |
| `scroll_events_90d` | number | GA4 scroll events |
| `days_with_impressions` | number | Days in the 90-day window with ≥ 1 impression (0–90) |
| `days_with_sessions` | number | Days in the window with ≥ 1 session (0–90) |

## 30-day comparison windows (the trend inputs)

| Column | Type | Meaning |
|---|---|---|
| `impressions_last_30d` | number | Impressions in the most recent 30 days |
| `clicks_last_30d` | number | Clicks, most recent 30 days |
| `sessions_last_30d` | number | Sessions, most recent 30 days |
| `impressions_prev_30d` | number | Impressions in the 30 days before that (days 31–60 back) |
| `clicks_prev_30d` | number | Clicks, days 31–60 back |
| `sessions_prev_30d` | number | Sessions, days 31–60 back |

## Derived rates (all ×100 percentages)

| Column | Formula | Notes |
|---|---|---|
| `ctr` | `clicks_90d / impressions_90d × 100` | 2 decimals. `0.76` = 0.76% |
| `avg_position` | mean GSC position over the window | 1 decimal. Lower is better. **`0` means "no position data", not position zero** (1,205 rows) |
| `engagement_rate` | `engaged_sessions_90d / sessions_90d × 100` | 0–100 |
| `scroll_rate` | `scroll_events_90d / pageviews_90d × 100` | **Can exceed 100** (multiple scroll events per pageview); blank when `pageviews_90d = 0` |
| `ai_traffic_pct` | `ai_sessions_90d / sessions_90d × 100` | **Can exceed 100** (AI-referred sessions are measured independently of total GA4 sessions) |
| `trend_pct` | `(impressions_last_30d − impressions_prev_30d) / impressions_prev_30d × 100` | 1 decimal. Blank when `impressions_prev_30d = 0` (3,388 rows; the prep step fills blanks with 0). **Label source — never a feature** |

## Buckets / tiers (transparent, threshold-based)

| Column | Values | Rule |
|---|---|---|
| `age_tier` | `0-14`, `15-30`, `31-90`, `91-180`, `181-365`, `365+` | From `content_age_days`. This slice only contains `31-90` and up |
| `age_tier_order` | 1–6 | Numeric order of `age_tier` (1 = youngest) |
| `freshness_tier` | `never`, `0-30`, `31-90`, `91-180`, `181+` | From `days_since_last_update`; `never` = no update recorded (0 rows in this slice) |
| `word_count_tier` | `<1000`, `1000-2000`, `2000-3500`, `3500+` | Blank when `word_count` is blank |
| `char_count_tier` | `<8000`, `8000-15000`, `15000-25000`, `25000+` | Blank when `char_count` is blank |
| `impression_tier` | `no_data`, `none`, `low`, `moderate`, `good`, `excellent` | `no_data` = client has no GSC; `none` = 0; `low` > 0; `moderate` ≥ 300; `good` ≥ 3,000; `excellent` ≥ 30,000 |
| `position_tier` | `no_data`, `top_3`, `page_1`, `striking`, `page_3_5`, `deep` | avg position ≤ 3 / ≤ 10 / ≤ 20 / ≤ 50 / > 50. ⚠️ Tier metrics need a volume floor: this slice's `top_3` stratum has median volume ~53 impressions/90d, where one click moves CTR by ~1.9pp — at warehouse scale positions 1–3 run ≈ 2.78% CTR. Never read a tier median without stating its volume floor |
| `trend_direction` | `new`, `flat`, `up`, `down`, `stable` | last-30d vs prev-30d impressions: `new` = prev 0 & last > 0; `flat` = both 0; `up` > +20%; `down` < −20%; else `stable`. **Label source — never a feature** |


... (61 more lines)

===========================================================================
FILE: work/README.md
===========================================================================
# work/ — your space

Everything you build lives here: lane experiments, notebooks, figures, and your capstone
report. The rest of the repo is the shared reference; this folder is yours.

## Rules of the road

1. **Copy, don't edit.** Need to change the pipeline? Copy the script here
   (e.g. `work/scripts/03_train_model_v2.py`) or adjust the feature lists in
   `scripts/ml_utils.py`. The reference pipeline in `scripts/` stays pristine — it's the
   baseline you compare against, and reviewers expect to find it unchanged.
2. **No datasets in git.** CSVs inside `work/` are gitignored, and CI fails if any dataset
   CSV is committed anywhere in the repo. Small summary tables belong in your report as
   markdown, not as data files. Metrics JSONs are the opposite: keep files like
   `work/outputs/*.json` **committed** — they are the receipts your report's numbers trace
   back to. Don't add ignore rules that hide them.
3. **Stay reproducible.** Fix your random seeds and note them in your report. Someone with a
   fresh clone should be able to re-run your work from your instructions alone.
4. **Public-safety language.** Everything here may end up public with your submission:
   observed / measured / directional / decision-support — no client-identifying details,
   no causal claims without a design (see `DATA_USE.md`).

## Suggested layout

```text
work/
  notebooks/            your experiment notebooks
  scripts/              copied + modified pipeline pieces
  figures/              charts for your report
  capstone_report.md    your capstone write-up (start from the template)
```

## Capstone

Copy `capstone_report_template.md` to `capstone_report.md` and fill it in as you go — it
mirrors the eight axes your work is graded on, so writing it early keeps you honest.

## Your assignment index

Your skeleton notebooks are already in `notebooks/` — one per assignment, pre-named.

In [13]:
from pathlib import Path
import json

notebook_path = Path(
    "/content/jsk-flyrank-ml-internship/work/notebooks/w03_data_contract.ipynb"
)

nb = json.loads(notebook_path.read_text(encoding="utf-8"))

for i, cell in enumerate(nb["cells"]):
    cell_type = cell["cell_type"]
    source = "".join(cell.get("source", []))

    print("\n" + "=" * 75)
    print(f"CELL {i} | {cell_type}")
    print("=" * 75)
    print(source[:5000])

    if cell.get("outputs"):
        print("\n[Saved output preview]")
        for output in cell["outputs"]:
            if "text" in output:
                print("".join(output["text"])[:1200])
            elif "data" in output:
                for mime, content in output["data"].items():
                    if mime in ("text/plain", "text/markdown"):
                        print(str(content)[:1200])

===========================================================================
CELL 0 | markdown
===========================================================================
<a href="https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

===========================================================================
CELL 1 | markdown
===========================================================================
# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ch-jsk/jsk-flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

===========================================================================
CELL 2 | markdown
===========================================================================
## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

**Unit of analysis**

One row represents the performance of one content item for one client on one reporting date.

**Tables used**

- dim_content
- fact_content_daily_performance

**Time window**

I will work with a mid-panel month (March 2026) rather than the final month because the final month should remain isolated from feature development and label construction.

**Lane**

CTR / Engagement Opportunity Scoring (Lane 4)

**Output**

A ranked list of pages whose CTR appears lower than expected for similar search-position tiers.

===========================================================================
CELL 3 | code
===========================================================================
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

print("Lane:", "CTR / Engagement Opportunity Scoring")
print("Month:", "2026-03")

[Saved output preview]
Lane: CTR / Engagement Opportunity Scoring
Month: 2026-03


===========================================================================
CELL 4 | markdown
===========================================================================
## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

**Features**
- impressions
- clicks
- ctr
- gsc_avg_position
- content_age_days

**Label or proxy**
- expected CTR gap
- optimisation priority score

**Context fields**
- report_date
- client_id
- content_id

**Excluded fields**
- trend_direction
- trend_pct
- is_declining_label

These variables are excluded because they contain information derived from the outcome itself and may introduce leakage.

===========================================================================
CELL 5 | code
===========================================================================
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

features = [
    "impressions",
    "clicks",
    "ctr",
    "gsc_avg_position",
    "content_age_days",
]

excluded = [
    "trend_direction",
    "trend_pct",
    "is_declining_label",
]

print("Features")
print(features)

print("\nExcluded")
print(excluded)


[Saved output preview]
Features
['impressions', 'clicks', 'ctr', 'gsc_avg_position', 'content_age_days']

Excluded
['trend_direction', 'trend_pct', 'is_declining_label']


===========================================================================
CELL 6 | markdown
===========================================================================
## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

The following checks verify the grain of the data, the available date range, and the presence of missing values.

===========================================================================
CELL 7 | code
===========================================================================
!pip install -q datasets huggingface_hub pyarrow pandas

===========================================================================
CELL 8 | code
===========================================================================
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

print(HF_TOKEN[:1])

[Saved output preview]
h


===========================================================================
CELL 9 | code
===========================================================================
from huggingface_hub import login

login(token=HF_TOKEN)

===========================================================================
CELL 10 | code
===========================================================================
from datasets import load_dataset

dim_content = load_dataset(
    "FlyRank/internship-warehouse",
    "dim_content",
    token=HF_TOKEN
)

===========================================================================
CELL 11 | code
===========================================================================
print(dim_content)

[Saved output preview]
DatasetDict({
    train: Dataset({
        features: ['client_hash_id', 'content_hash_id', 'keyword_hash_id', 'url_hash_id', 'keyword_char_count', 'keyword_token_count', 'url_char_count', 'content_created_date', 'content_updated_date', 'content_type', 'search_volume', 'competition', 'competition_level', 'cpc', 'main_intent', 'backlinks', 'category_count', 'keyword_created_date', 'provider_used', 'model_used', 'char_count', 'word_count', 'last_optimized_date', 'optimization_eligible_date', 'is_published', 'is_deleted'],
        num_rows: 519606
    })
})


===========================================================================
CELL 12 | code
===========================================================================
df = dim_content["train"].to_pandas()

print(df.shape)
df.head()

[Saved output preview]
(519606, 26)

['            client_hash_id           content_hash_id  \\\n', '0  client_04660893ae39614a  content_004de9653278b5a4   \n', '1  client_04660893ae39614a  content_00dc5efae381b2ab   \n', '2  client_04660893ae39614a  content_01410f2556c327ac   \n', '3  client_04660893ae39614a  content_019f27f634053ca7   \n', '4  client_04660893ae39614a  content_01efa71faea45dcc   \n', '\n', '            keyword_hash_id           url_hash_id  keyword_char_count  \\\n', '0  keyword_e754999ab88dd9f2  url_d6091f18cf628794                  22   \n', '1  keyword_4329d7aede8e208b  url_3a66d2f2e36823ca                  31   \n', '2  keyword_9b08047d3d2a0406  url_809eda7a7e20b3b2                  22   \n', '3  keyword_e7cec7ab1804c1c2  url_5fb42bafc4399861                  14   \n', '4  keyword_56b0062a1d8b7524  url_ece0abc3e5fb75f9                  24   \n', '\n', '   keyword_token_count  url_char_count content_created_date  \\\n', '0                    4             108           2026-05-30   \n', '1                    6              95           2026-06-12   \n', '2                    5              82           2026-05-09   \n', '3                    3              92           2026-06-15   \n', '4

===========================================================================
CELL 13 | code
===========================================================================
#Verify the grain
print("Rows:", len(df))
print("Unique content IDs:", df["content_hash_id"].nunique())

[Saved output preview]
Rows: 519606
Unique content IDs: 519606


===========================================================================
CELL 14 | code
===========================================================================
#Verify the date span
date_cols = [col for col in df.columns if "date" in col.lower()]
print(date_cols)

[Saved output preview]
['content_created_date', 'content_updated_date', 'keyword_created_date', 'last_optimized_date', 'optimization_eligible_date']


===========================================================================
CELL 15 | code
===========================================================================
for col in date_cols:
    print("\n", col)

    values = df[col].dropna()

    print("Minimum:", values.min())
    print("Maximum:", values.max())

[Saved output preview]

 content_created_date
Minimum: 2024-10-16
Maximum: 2026-07-06

 content_updated_date
Minimum: 2024-10-28
Maximum: 2026-07-06

 keyword_created_date
Minimum: 2024-10-16
Maximum: 2026-07-02

 last_optimized_date
Minimum: 2026-04-24
Maximum: 2026-07-06

 optimization_eligible_date
Minimum: 2026-06-08
Maximum: 2026-08-20


===========================================================================
CELL 16 | code
===========================================================================
#Verify missing values
missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

print(missing.head(10))

[Saved output preview]
optimization_eligible_date    474210
last_optimized_date           474210
provider_used                 369936
backlinks                     267474
word_count                    177768
char_count                    177768
main_intent                   148398
competition_level             144456
cpc                           142622
search_volume                 142622
dtype: int64


===========================================================================
CELL 17 | code
===========================================================================
#See all available columns
print(df.columns.tolist())

[Saved output preview]
['client_hash_id', 'content_hash_id', 'keyword_hash_id', 'url_hash_id', 'keyword_char_count', 'keyword_token_count', 'url_char_count', 'content_created_date', 'content_updated_date', 'content_type', 'search_volume', 'competition', 'competition_level', 'cpc', 'main_intent', 'backlinks', 'category_count', 'keyword_created_date', 'provider_used', 'model_used', 'char_count', 'word_count', 'last_optimized_date', 'optimization_eligible_date', 'is_published', 'is_deleted']


===========================================================================
CELL 18 | markdown
===========================================================================
### Verification results

The following checks were performed to verify the contract.

- The number of unique content identifiers matches the number of rows.
- The content table spans from late 2024 to mid-2026.
- Missing values were identified and examined before feature selection.
- The structure of the data was inspected to ensure that the selected features were available at the decision point.

===========================================================================
CELL 19 | markdown
===========================================================================
## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

- Historical depth differs across clients.
- Some columns contain large numbers of missing values.
- Search position strongly affects CTR.
- Metadata alone cannot fully explain user behaviour.
- Observed patterns should be treated as decision-support signals rather than causal relationships.

===========================================================================
CELL 20 | code
===========================================================================
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.


===========================================================================
CELL 21 | markdown
===========================================================================
## Self-check

Before you submit, confirm each line honestly:

- [x] Every section above is filled — markdown thinking AND the code that backs it
- [x] The notebook runs top to bottom with no errors (Runtime → Run all)
- [x] No client names, URLs, or private queries anywhere
- [x] My claims use careful words: observed, measured, directional, decision-support
- [x] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.

===========================================================================
CELL 22 | code
===========================================================================

In [14]:
%pip install -q "duckdb>=1.4.0"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.6/21.6 MB 30.1 MB/s eta 0:00:00

In [15]:
import duckdb
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

if not HF_TOKEN:
    raise RuntimeError(
        "HF_TOKEN was not found in Colab Secrets. "
        "Add it in the Colab Secrets panel and enable notebook access."
    )

con = duckdb.connect("/content/flyrank_capstone.duckdb")

con.execute("INSTALL httpfs")
con.execute("LOAD httpfs")

# Keep the token out of notebook output.
con.execute("""
    CREATE OR REPLACE SECRET hf_token (
        TYPE huggingface,
        TOKEN ?
    )
""", [HF_TOKEN])

print("DuckDB version:", duckdb.__version__)
print("DuckDB connection ready.")
print("Token retrieved without displaying its value.")

DuckDB version: 1.5.6
DuckDB connection ready.
Token retrieved without displaying its value.

In [16]:
from huggingface_hub import HfApi

api = HfApi(token=HF_TOKEN)
repo_id = "FlyRank/internship-warehouse"

files = api.list_repo_files(
    repo_id=repo_id,
    repo_type="dataset"
)

print("Total files listed:", len(files))

for name in files:
    if any(key in name.lower() for key in [
        "fact_content_daily_performance",
        "dim_content",
        "dim_clients",
        "manifest",
        "readme"
    ]):
        print(name)

Total files listed: 24
README.md
dim_clients.parquet
dim_content.parquet
fact_content_daily_performance/month=2025-01/data_0.parquet
fact_content_daily_performance/month=2025-02/data_0.parquet
fact_content_daily_performance/month=2025-03/data_0.parquet
fact_content_daily_performance/month=2025-04/data_0.parquet
fact_content_daily_performance/month=2025-05/data_0.parquet
fact_content_daily_performance/month=2025-06/data_0.parquet
fact_content_daily_performance/month=2025-07/data_0.parquet
fact_content_daily_performance/month=2025-08/data_0.parquet
fact_content_daily_performance/month=2025-09/data_0.parquet
fact_content_daily_performance/month=2025-10/data_0.parquet
fact_content_daily_performance/month=2025-11/data_0.parquet
fact_content_daily_performance/month=2025-12/data_0.parquet
fact_content_daily_performance/month=2026-01/data_0.parquet
fact_content_daily_performance/month=2026-02/data_0.parquet
fact_content_daily_performance/month=2026-03/data_0.parquet
fact_content_daily_performance/month=2026-04/data_0.parquet
fact_content_daily_performance/month=2026-05/data_0.parquet
fact_content_daily_performance/month=2026-06/data_0.parquet
fact_content_daily_performance_sample.parquet

In [18]:
import duckdb

march_path = (
    "hf://datasets/FlyRank/internship-warehouse/"
    "fact_content_daily_performance/month=2026-03/data_0.parquet"
)

# 1. Inspect column names and types without loading the table into pandas.
schema = con.execute(
    f"DESCRIBE SELECT * FROM read_parquet('{march_path}')"
).fetchdf()

print("MARCH PARTITION SCHEMA")
display(schema)

# 2. Inspect a few rows to verify the actual field names and values.
sample = con.execute(
    f"SELECT * FROM read_parquet('{march_path}') LIMIT 5"
).fetchdf()

print("\nSAMPLE ROWS")
display(sample)

MARCH PARTITION SCHEMA

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

SAMPLE ROWS

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,<NA>,20,0,67,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,<NA>,1,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,<NA>,125,1,616,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,<NA>,7,0,28,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,<NA>,11,0,25,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03

In [19]:
march_quality = con.execute(f"""
    SELECT
        COUNT(*) AS total_rows,
        COUNT(DISTINCT report_date) AS reporting_days,
        MIN(report_date) AS first_report_date,
        MAX(report_date) AS last_report_date,
        COUNT(DISTINCT client_hash_id) AS distinct_clients,
        COUNT(DISTINCT content_hash_id) AS distinct_content_items,
        COUNT(*) FILTER (
            WHERE gsc_data_available IS TRUE
        ) AS rows_with_gsc_data,
        COUNT(*) FILTER (
            WHERE ga4_data_available IS TRUE
        ) AS rows_with_ga4_data,
        COUNT(*) FILTER (
            WHERE gsc_impressions IS NULL
        ) AS null_impressions,
        COUNT(*) FILTER (
            WHERE gsc_clicks IS NULL
        ) AS null_clicks,
        COUNT(*) FILTER (
            WHERE gsc_avg_position IS NULL
        ) AS null_positions
    FROM read_parquet('{march_path}')
""").fetchdf()

display(march_quality)

duplicate_check = con.execute(f"""
    SELECT COUNT(*) AS duplicate_grain_groups
    FROM (
        SELECT report_date, client_hash_id, content_hash_id
        FROM read_parquet('{march_path}')
        GROUP BY report_date, client_hash_id, content_hash_id
        HAVING COUNT(*) > 1
    ) duplicates
""").fetchdf()

display(duplicate_check)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,total_rows,reporting_days,first_report_date,last_report_date,distinct_clients,distinct_content_items,rows_with_gsc_data,rows_with_ga4_data,null_impressions,null_clicks,null_positions
0,9841378,31,2026-03-01,2026-03-31,55,331437,3611061,413966,0,0,6230317

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   duplicate_grain_groups
0                       0

In [20]:
dimension_paths = {
    "dim_content": (
        "hf://datasets/FlyRank/internship-warehouse/dim_content.parquet"
    ),
    "dim_clients": (
        "hf://datasets/FlyRank/internship-warehouse/dim_clients.parquet"
    ),
}

for table_name, path in dimension_paths.items():
    print(f"\n{'=' * 60}\n{table_name}\n{'=' * 60}")

    result = con.execute(
        f"DESCRIBE SELECT * FROM read_parquet('{path}')"
    ).fetchdf()

    display(result)

============================================================
dim_content
============================================================

                   column_name column_type null   key default extra
0               client_hash_id     VARCHAR  YES  None    None  None
1              content_hash_id     VARCHAR  YES  None    None  None
2              keyword_hash_id     VARCHAR  YES  None    None  None
3                  url_hash_id     VARCHAR  YES  None    None  None
4           keyword_char_count      BIGINT  YES  None    None  None
5          keyword_token_count      BIGINT  YES  None    None  None
6               url_char_count      BIGINT  YES  None    None  None
7         content_created_date        DATE  YES  None    None  None
8         content_updated_date        DATE  YES  None    None  None
9                 content_type     VARCHAR  YES  None    None  None
10               search_volume      BIGINT  YES  None    None  None
11                 competition      DOUBLE  YES  None    None  None
12           competition_level     VARCHAR  YES  None    None  None
13                         cpc      DOUBLE  YES  None    None  None
14                 main_intent     VARCHAR  YES  None    None  None
15                   backlinks      BIGINT  YES  None    None  None
16              category_count      BIGINT  YES  None    None  None
17        keyword_created_date        DATE  YES  None    None  None
18               provider_used     VARCHAR  YES  None    None  None
19                  model_used     VARCHAR  YES  None    None  None
20                  char_count      BIGINT  YES  None    None  None
21                  word_count      BIGINT  YES  None    None  None
22         last_optimized_date        DATE  YES  None    None  None
23  optimization_eligible_date        DATE  YES  None    None  None
24                is_published     BOOLEAN  YES  None    None  None
25                  is_deleted     BOOLEAN  YES  None    None  None

============================================================
dim_clients
============================================================

           column_name column_type null   key default extra
0       client_hash_id     VARCHAR  YES  None    None  None
1            is_active     BOOLEAN  YES  None    None  None
2       has_gsc_access     BOOLEAN  YES  None    None  None
3       has_ga4_access     BOOLEAN  YES  None    None  None
4       access_profile     VARCHAR  YES  None    None  None
5  client_created_date        DATE  YES  None    None  None
6  client_updated_date        DATE  YES  None    None  None
7       gsc_data_start        DATE  YES  None    None  None
8       ga4_data_start        DATE  YES  None    None  None

In [21]:
content_path = (
    "hf://datasets/FlyRank/internship-warehouse/dim_content.parquet"
)
clients_path = (
    "hf://datasets/FlyRank/internship-warehouse/dim_clients.parquet"
)

content_key_check = con.execute(f"""
    SELECT
        COUNT(*) AS rows,
        COUNT(DISTINCT content_hash_id) AS unique_content_ids,
        COUNT(*) FILTER (
            WHERE content_hash_id IS NULL
        ) AS null_content_ids,
        COUNT(*) FILTER (
            WHERE client_hash_id IS NULL
               OR content_hash_id IS NULL
        ) AS rows_with_null_join_keys
    FROM read_parquet('{content_path}')
""").fetchdf()

client_key_check = con.execute(f"""
    SELECT
        COUNT(*) AS rows,
        COUNT(DISTINCT client_hash_id) AS unique_client_ids,
        COUNT(*) FILTER (
            WHERE client_hash_id IS NULL
        ) AS null_client_ids
    FROM read_parquet('{clients_path}')
""").fetchdf()

print("Content dimension")
display(content_key_check)

print("Client dimension")
display(client_key_check)

duplicate_content_keys = con.execute(f"""
    SELECT COUNT(*) AS duplicate_client_content_keys
    FROM (
        SELECT client_hash_id, content_hash_id
        FROM read_parquet('{content_path}')
        GROUP BY client_hash_id, content_hash_id
        HAVING COUNT(*) > 1
    ) d
""").fetchdf()

print("Duplicate client-content keys")
display(duplicate_content_keys)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Content dimension

     rows  unique_content_ids  null_content_ids  rows_with_null_join_keys
0  519606              519606                 0                         0

Client dimension

   rows  unique_client_ids  null_client_ids
0   104                104                0

Duplicate client-content keys

   duplicate_client_content_keys
0                              0

In [22]:
# March 2026 development table — DuckDB aggregation
# June 2026 is not accessed by this query.

con.execute(f"""
CREATE OR REPLACE TABLE march_dev AS
WITH monthly AS (
    SELECT
        client_hash_id,
        content_hash_id,

        COUNT(DISTINCT report_date) AS calendar_days_observed,

        COUNT(DISTINCT report_date)
            FILTER (WHERE gsc_data_available IS TRUE)
            AS gsc_days_available,

        COUNT(DISTINCT report_date)
            FILTER (WHERE ga4_data_available IS TRUE)
            AS ga4_days_available,

        SUM(gsc_impressions)
            FILTER (WHERE gsc_data_available IS TRUE)
            AS impressions_march,

        SUM(gsc_clicks)
            FILTER (WHERE gsc_data_available IS TRUE)
            AS clicks_march,

        SUM(gsc_sum_position)
            FILTER (WHERE gsc_data_available IS TRUE)
            AS position_sum_march,

        SUM(gsc_impressions)
            FILTER (
                WHERE gsc_data_available IS TRUE
                  AND gsc_avg_position IS NOT NULL
            ) AS impressions_with_position,

        SUM(ga4_sessions)
            FILTER (WHERE ga4_data_available IS TRUE)
            AS sessions_march,

        SUM(ga4_engaged_sessions)
            FILTER (WHERE ga4_data_available IS TRUE)
            AS engaged_sessions_march,

        SUM(ga4_pageviews)
            FILTER (WHERE ga4_data_available IS TRUE)
            AS pageviews_march,

        SUM(scroll_events)
            FILTER (WHERE ga4_data_available IS TRUE)
            AS scroll_events_march

    FROM read_parquet('{march_path}')
    WHERE report_date >= DATE '2026-03-01'
      AND report_date <  DATE '2026-04-01'
    GROUP BY client_hash_id, content_hash_id
)
SELECT
    m.*,

    100.0 * clicks_march
        / NULLIF(impressions_march, 0) AS ctr_march_pct,

    position_sum_march::DOUBLE
        / NULLIF(impressions_with_position, 0)
        AS weighted_position_march,

    100.0 * engaged_sessions_march
        / NULLIF(sessions_march, 0)
        AS engagement_rate_march_pct,

    100.0 * scroll_events_march
        / NULLIF(pageviews_march, 0)
        AS scroll_events_per_100_pageviews,

    c.content_type,
    c.content_created_date,
    c.content_updated_date,
    c.search_volume,
    c.competition,
    c.main_intent,
    c.word_count,

    cl.gsc_data_start,
    cl.ga4_data_start

FROM monthly m
LEFT JOIN read_parquet('{content_path}') c
    ON m.client_hash_id = c.client_hash_id
   AND m.content_hash_id = c.content_hash_id
LEFT JOIN read_parquet('{clients_path}') cl
    ON m.client_hash_id = cl.client_hash_id
""")

print("March development table created.")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

March development table created.

In [23]:
# Aggregate checks only; do not display individual page identifiers.

march_summary = con.execute("""
    SELECT
        COUNT(*) AS client_content_pairs,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(DISTINCT content_hash_id) AS content_items,

        COUNT(*) FILTER (
            WHERE content_type IS NULL
        ) AS unmatched_content_dimension,

        COUNT(*) FILTER (
            WHERE gsc_data_start IS NULL
        ) AS unmatched_client_dimension,

        COUNT(*) FILTER (
            WHERE impressions_march > 0
        ) AS pairs_with_search_impressions,

        COUNT(*) FILTER (
            WHERE impressions_march > 0
              AND ctr_march_pct IS NOT NULL
        ) AS pairs_with_defined_ctr,

        COUNT(*) FILTER (
            WHERE weighted_position_march IS NOT NULL
        ) AS pairs_with_position,

        COUNT(*) FILTER (
            WHERE sessions_march IS NOT NULL
        ) AS pairs_with_ga4_sessions

    FROM march_dev
""").fetchdf()

display(march_summary)

print("\nCTR distribution (percentage points):")

display(con.execute("""
    SELECT
        COUNT(*) AS n,
        ROUND(AVG(ctr_march_pct), 4) AS mean_ctr_pct,
        ROUND(MEDIAN(ctr_march_pct), 4) AS median_ctr_pct,
        ROUND(QUANTILE_CONT(ctr_march_pct, 0.75), 4) AS p75_ctr_pct,
        ROUND(AVG(weighted_position_march), 3) AS mean_position
    FROM march_dev
    WHERE impressions_march > 0
      AND ctr_march_pct IS NOT NULL
""").fetchdf())

,client_content_pairs,clients,content_items,unmatched_content_dimension,unmatched_client_dimension,pairs_with_search_impressions,pairs_with_defined_ctr,pairs_with_position,pairs_with_ga4_sessions
0,331437,55,331437,0,7067,176738,176738,176738,90489

CTR distribution (percentage points):

        n  mean_ctr_pct  median_ctr_pct  p75_ctr_pct  mean_position
0  176738        0.4594             0.0       0.2158         15.992

In [24]:
client_join_audit = con.execute(f"""
WITH march_clients AS (
    SELECT DISTINCT client_hash_id
    FROM read_parquet('{march_path}')
),
known_clients AS (
    SELECT client_hash_id
    FROM read_parquet('{clients_path}')
)
SELECT
    COUNT(*) AS distinct_march_clients,
    COUNT(*) FILTER (
        WHERE k.client_hash_id IS NOT NULL
    ) AS clients_with_dimension_match,
    COUNT(*) FILTER (
        WHERE k.client_hash_id IS NULL
    ) AS clients_without_dimension_match
FROM march_clients m
LEFT JOIN known_clients k
    ON m.client_hash_id = k.client_hash_id
""").fetchdf()

display(client_join_audit)

print("Pairs by client-dimension match:")

display(con.execute("""
    SELECT
        CASE
            WHEN gsc_data_start IS NULL
                THEN 'Missing client dimension or GSC start date'
            ELSE 'Client dimension matched'
        END AS client_metadata_status,
        COUNT(*) AS client_content_pairs,
        COUNT(*) FILTER (
            WHERE impressions_march > 0
        ) AS pairs_with_impressions
    FROM march_dev
    GROUP BY 1
    ORDER BY 1
""").fetchdf())

,distinct_march_clients,clients_with_dimension_match,clients_without_dimension_match
0,55,55,0

Pairs by client-dimension match:

,client_metadata_status,client_content_pairs,pairs_with_impressions
0,Client dimension matched,324370,176738
1,Missing client dimension or GSC start date,7067,0

In [25]:
# April 2026 outcome aggregation — historical development only.
# June 2026 remains untouched.

april_path = (
    "hf://datasets/FlyRank/internship-warehouse/"
    "fact_content_daily_performance/month=2026-04/data_0.parquet"
)

con.execute(f"""
CREATE OR REPLACE TABLE april_outcomes AS
SELECT
    client_hash_id,
    content_hash_id,

    COUNT(DISTINCT report_date)
        FILTER (WHERE gsc_data_available IS TRUE)
        AS gsc_days_available_april,

    SUM(gsc_impressions)
        FILTER (WHERE gsc_data_available IS TRUE)
        AS impressions_april,

    SUM(gsc_clicks)
        FILTER (WHERE gsc_data_available IS TRUE)
        AS clicks_april,

    SUM(gsc_sum_position)
        FILTER (
            WHERE gsc_data_available IS TRUE
              AND gsc_avg_position IS NOT NULL
        ) AS position_sum_april,

    SUM(gsc_impressions)
        FILTER (
            WHERE gsc_data_available IS TRUE
              AND gsc_avg_position IS NOT NULL
        ) AS impressions_with_position_april

FROM read_parquet('{april_path}')
WHERE report_date >= DATE '2026-04-01'
  AND report_date < DATE '2026-05-01'
GROUP BY client_hash_id, content_hash_id
""")

con.execute("""
CREATE OR REPLACE TABLE april_outcomes_scored AS
SELECT
    *,
    100.0 * clicks_april
        / NULLIF(impressions_april, 0) AS ctr_april_pct,

    position_sum_april::DOUBLE
        / NULLIF(impressions_with_position_april, 0)
        AS weighted_position_april

FROM april_outcomes
""")

print("April outcome table created.")

print("\nApril coverage summary:")
display(con.execute("""
    SELECT
        COUNT(*) AS client_content_pairs,
        COUNT(*) FILTER (
            WHERE impressions_april > 0
        ) AS pairs_with_impressions,
        COUNT(*) FILTER (
            WHERE impressions_april >= 100
        ) AS pairs_with_at_least_100_impressions,
        COUNT(*) FILTER (
            WHERE impressions_april >= 300
        ) AS pairs_with_at_least_300_impressions,
        COUNT(*) FILTER (
            WHERE ctr_april_pct IS NOT NULL
        ) AS pairs_with_defined_ctr,
        COUNT(*) FILTER (
            WHERE weighted_position_april IS NOT NULL
        ) AS pairs_with_position
    FROM april_outcomes_scored
""").fetchdf())

print("\nApril impression distribution:")
display(con.execute("""
    SELECT
        COUNT(*) AS n_with_positive_impressions,
        ROUND(QUANTILE_CONT(impressions_april, 0.25), 1) AS p25,
        ROUND(QUANTILE_CONT(impressions_april, 0.50), 1) AS median,
        ROUND(QUANTILE_CONT(impressions_april, 0.75), 1) AS p75,
        ROUND(QUANTILE_CONT(impressions_april, 0.90), 1) AS p90,
        ROUND(QUANTILE_CONT(impressions_april, 0.95), 1) AS p95
    FROM april_outcomes_scored
    WHERE impressions_april > 0
""").fetchdf())

print("\nApril CTR distribution among pairs with at least 100 impressions:")
display(con.execute("""
    SELECT
        COUNT(*) AS n,
        ROUND(AVG(ctr_april_pct), 4) AS mean_ctr_pct,
        ROUND(MEDIAN(ctr_april_pct), 4) AS median_ctr_pct,
        ROUND(QUANTILE_CONT(ctr_april_pct, 0.25), 4) AS p25_ctr_pct,
        ROUND(QUANTILE_CONT(ctr_april_pct, 0.75), 4) AS p75_ctr_pct
    FROM april_outcomes_scored
    WHERE impressions_april >= 100
      AND ctr_april_pct IS NOT NULL
""").fetchdf())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

April outcome table created.

April coverage summary:

,client_content_pairs,pairs_with_impressions,pairs_with_at_least_100_impressions,pairs_with_at_least_300_impressions,pairs_with_defined_ctr,pairs_with_position
0,362172,194760,107144,75963,194760,194760

April impression distribution:

   n_with_positive_impressions   p25  median    p75     p90     p95
0                       194760  21.0   141.0  837.0  3386.0  7028.0

April CTR distribution among pairs with at least 100 impressions:

        n  mean_ctr_pct  median_ctr_pct  p25_ctr_pct  p75_ctr_pct
0  107144        0.2479           0.094          0.0       0.3398

In [26]:
position_tier_audit = con.execute("""
WITH tiered AS (
    SELECT
        CASE
            WHEN weighted_position_april <= 3 THEN 'top_3'
            WHEN weighted_position_april <= 10 THEN 'positions_4_10'
            WHEN weighted_position_april <= 20 THEN 'positions_11_20'
            WHEN weighted_position_april <= 50 THEN 'positions_21_50'
            ELSE 'positions_51_plus'
        END AS position_tier,
        impressions_april,
        ctr_april_pct
    FROM april_outcomes_scored
    WHERE impressions_april > 0
      AND weighted_position_april IS NOT NULL
      AND ctr_april_pct IS NOT NULL
),
thresholds AS (
    SELECT 100 AS impression_floor
    UNION ALL
    SELECT 300 AS impression_floor
)
SELECT
    t.impression_floor,
    a.position_tier,
    COUNT(*) AS n_pages,
    ROUND(100.0 * AVG(
        CASE WHEN a.ctr_april_pct = 0 THEN 1.0 ELSE 0.0 END
    ), 2) AS zero_ctr_pct,
    ROUND(QUANTILE_CONT(a.ctr_april_pct, 0.25), 4) AS ctr_p25_pct,
    ROUND(MEDIAN(a.ctr_april_pct), 4) AS ctr_median_pct,
    ROUND(QUANTILE_CONT(a.ctr_april_pct, 0.75), 4) AS ctr_p75_pct
FROM tiered a
CROSS JOIN thresholds t
WHERE a.impressions_april >= t.impression_floor
GROUP BY t.impression_floor, a.position_tier
ORDER BY t.impression_floor, a.position_tier
""").fetchdf()

display(position_tier_audit)

,impression_floor,position_tier,n_pages,zero_ctr_pct,ctr_p25_pct,ctr_median_pct,ctr_p75_pct
0,100,positions_11_20,22864,47.43,0.0000,0.0638,0.3300
1,100,positions_21_50,24784,56.41,0.0000,0.0000,0.1493
2,100,positions_4_10,49889,28.14,0.0000,0.1847,0.4351
3,100,positions_51_plus,4106,90.28,0.0000,0.0000,0.0000
4,100,top_3,5501,31.98,0.0000,0.1460,0.4168
5,300,positions_11_20,15056,32.93,0.0000,0.1500,0.3322
6,300,positions_21_50,15869,40.90,0.0000,0.0512,0.1861
7,300,positions_4_10,39193,18.08,0.0705,0.2089,0.4351
8,300,positions_51_plus,1259,80.78,0.0000,0.0000,0.0000
9,300,top_3,4586,22.81,0.0339,0.1849,0.4444

In [27]:
cohort_size_audit = con.execute("""
SELECT
    COUNT(*) FILTER (
        WHERE impressions_april >= 100
          AND weighted_position_april IS NOT NULL
    ) AS eligible_at_100,

    COUNT(*) FILTER (
        WHERE impressions_april >= 300
          AND weighted_position_april IS NOT NULL
    ) AS eligible_at_300,

    COUNT(DISTINCT client_hash_id) FILTER (
        WHERE impressions_april >= 100
          AND weighted_position_april IS NOT NULL
    ) AS clients_at_100,

    COUNT(DISTINCT client_hash_id) FILTER (
        WHERE impressions_april >= 300
          AND weighted_position_april IS NOT NULL
    ) AS clients_at_300
FROM april_outcomes_scored
""").fetchdf()

display(cohort_size_audit)

   eligible_at_100  eligible_at_300  clients_at_100  clients_at_300
0           107144            75963              47              44

In [28]:
# Join historical March features to April outcomes.
# Uses March position for tier assignment; April position is not used.

con.execute("""
CREATE OR REPLACE TABLE march_april_cohort AS
SELECT
    m.client_hash_id,
    m.content_hash_id,

    m.impressions_march,
    m.clicks_march,
    m.ctr_march_pct,
    m.weighted_position_march,
    m.gsc_days_available,
    m.content_type,
    m.search_volume,
    m.word_count,

    a.impressions_april,
    a.clicks_april,
    a.ctr_april_pct,

    CASE
        WHEN m.weighted_position_march <= 3 THEN 'top_3'
        WHEN m.weighted_position_march <= 10 THEN 'positions_4_10'
        WHEN m.weighted_position_march <= 20 THEN 'positions_11_20'
        WHEN m.weighted_position_march <= 50 THEN 'positions_21_50'
        ELSE 'positions_51_plus'
    END AS march_position_tier

FROM march_dev m
INNER JOIN april_outcomes_scored a
    ON m.client_hash_id = a.client_hash_id
   AND m.content_hash_id = a.content_hash_id

WHERE m.impressions_march > 0
  AND m.ctr_march_pct IS NOT NULL
  AND m.weighted_position_march IS NOT NULL
  AND a.impressions_april >= 300
  AND a.ctr_april_pct IS NOT NULL
""")

print("March-to-April cohort size:")
display(con.execute("""
    SELECT
        COUNT(*) AS eligible_pairs,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(DISTINCT content_hash_id) AS content_items,
        COUNT(*) FILTER (
            WHERE impressions_march >= 100
        ) AS pairs_with_100_plus_march_impressions,
        COUNT(*) FILTER (
            WHERE impressions_march >= 300
        ) AS pairs_with_300_plus_march_impressions
    FROM march_april_cohort
""").fetchdf())

print("Cohort by March position tier:")
display(con.execute("""
    SELECT
        march_position_tier,
        COUNT(*) AS n_pairs,
        ROUND(AVG(ctr_march_pct), 4) AS mean_march_ctr_pct,
        ROUND(MEDIAN(ctr_march_pct), 4) AS median_march_ctr_pct,
        ROUND(AVG(ctr_april_pct), 4) AS mean_april_ctr_pct,
        ROUND(MEDIAN(ctr_april_pct), 4) AS median_april_ctr_pct,
        ROUND(100.0 * AVG(
            CASE WHEN ctr_april_pct = 0 THEN 1.0 ELSE 0.0 END
        ), 2) AS april_zero_ctr_pct
    FROM march_april_cohort
    GROUP BY march_position_tier
    ORDER BY
        CASE march_position_tier
            WHEN 'top_3' THEN 1
            WHEN 'positions_4_10' THEN 2
            WHEN 'positions_11_20' THEN 3
            WHEN 'positions_21_50' THEN 4
            ELSE 5
        END
""").fetchdf())

March-to-April cohort size:

,eligible_pairs,clients,content_items,pairs_with_100_plus_march_impressions,pairs_with_300_plus_march_impressions
0,69466,40,69466,67514,62985

Cohort by March position tier:

,march_position_tier,n_pairs,mean_march_ctr_pct,median_march_ctr_pct,mean_april_ctr_pct,median_april_ctr_pct,april_zero_ctr_pct
0,top_3,8275,0.3898,0.2428,0.3045,0.2034,18.69
1,positions_4_10,35087,0.3518,0.2240,0.2734,0.1814,21.23
2,positions_11_20,12351,0.2851,0.1661,0.2311,0.1255,34.25
3,positions_21_50,12613,0.1538,0.0671,0.1402,0.0540,39.38
4,positions_51_plus,1140,0.0456,0.0000,0.0489,0.0000,79.56

In [29]:
con.execute("""
CREATE OR REPLACE TABLE april_tier_reference AS
SELECT
    march_position_tier,
    COUNT(*) AS n_pairs,
    MEDIAN(ctr_april_pct) AS tier_median_ctr_april_pct,
    QUANTILE_CONT(ctr_april_pct, 0.25) AS tier_p25_ctr_april_pct,
    QUANTILE_CONT(ctr_april_pct, 0.75) AS tier_p75_ctr_april_pct
FROM march_april_cohort
GROUP BY march_position_tier
""")

con.execute("""
CREATE OR REPLACE TABLE opportunity_gap_audit AS
SELECT
    c.*,
    r.tier_median_ctr_april_pct,
    GREATEST(
        0.0,
        r.tier_median_ctr_april_pct - c.ctr_april_pct
    ) AS opportunity_gap_pp
FROM march_april_cohort c
JOIN april_tier_reference r
    USING (march_position_tier)
""")

print("April reference CTR by March position tier:")
display(con.execute("""
    SELECT
        march_position_tier,
        n_pairs,
        ROUND(tier_p25_ctr_april_pct, 4) AS tier_p25_ctr_pct,
        ROUND(tier_median_ctr_april_pct, 4) AS tier_median_ctr_pct,
        ROUND(tier_p75_ctr_april_pct, 4) AS tier_p75_ctr_pct
    FROM april_tier_reference
    ORDER BY
        CASE march_position_tier
            WHEN 'top_3' THEN 1
            WHEN 'positions_4_10' THEN 2
            WHEN 'positions_11_20' THEN 3
            WHEN 'positions_21_50' THEN 4
            ELSE 5
        END
""").fetchdf())

print("\nOpportunity-gap summary:")
display(con.execute("""
    SELECT
        COUNT(*) AS n_pairs,
        ROUND(AVG(opportunity_gap_pp), 4) AS mean_gap_pp,
        ROUND(MEDIAN(opportunity_gap_pp), 4) AS median_gap_pp,
        ROUND(QUANTILE_CONT(opportunity_gap_pp, 0.75), 4) AS p75_gap_pp,
        ROUND(QUANTILE_CONT(opportunity_gap_pp, 0.90), 4) AS p90_gap_pp,
        COUNT(*) FILTER (
            WHERE opportunity_gap_pp > 0
        ) AS pairs_below_tier_median,
        ROUND(
            100.0 * COUNT(*) FILTER (
                WHERE opportunity_gap_pp > 0
            ) / COUNT(*),
            2
        ) AS pct_below_tier_median
    FROM opportunity_gap_audit
""").fetchdf())

print("\nGap distribution by tier:")
display(con.execute("""
    SELECT
        march_position_tier,
        COUNT(*) AS n_pairs,
        COUNT(*) FILTER (
            WHERE opportunity_gap_pp > 0
        ) AS positive_gap_pairs,
        ROUND(AVG(opportunity_gap_pp), 4) AS mean_gap_pp,
        ROUND(MEDIAN(opportunity_gap_pp), 4) AS median_gap_pp
    FROM opportunity_gap_audit
    GROUP BY march_position_tier
    ORDER BY
        CASE march_position_tier
            WHEN 'top_3' THEN 1
            WHEN 'positions_4_10' THEN 2
            WHEN 'positions_11_20' THEN 3
            WHEN 'positions_21_50' THEN 4
            ELSE 5
        END
""").fetchdf())

April reference CTR by March position tier:

,march_position_tier,n_pairs,tier_p25_ctr_pct,tier_median_ctr_pct,tier_p75_ctr_pct
0,top_3,8275,0.0651,0.2034,0.4157
1,positions_4_10,35087,0.0488,0.1814,0.3774
2,positions_11_20,12351,0.0000,0.1255,0.3067
3,positions_21_50,12613,0.0000,0.0540,0.1940
4,positions_51_plus,1140,0.0000,0.0000,0.0000

Opportunity-gap summary:

,n_pairs,mean_gap_pp,median_gap_pp,p75_gap_pp,p90_gap_pp,pairs_below_tier_median,pct_below_tier_median
0,69466,0.0517,0.0,0.1045,0.1814,34161,49.18

Gap distribution by tier:

  march_position_tier  n_pairs  positive_gap_pairs  mean_gap_pp  median_gap_pp
0               top_3     8275                4137       0.0657            0.0
1      positions_4_10    35087               17543       0.0606            0.0
2     positions_11_20    12351                6175       0.0505            0.0
3     positions_21_50    12613                6306       0.0236            0.0
4   positions_51_plus     1140                   0       0.0000            0.0

In [30]:
# Correct eligibility: use March information, not future April volume.
# April outcomes are observed only where April GSC impressions exist.

con.execute("""
CREATE OR REPLACE TABLE march_april_cohort_v2 AS
SELECT
    m.client_hash_id,
    m.content_hash_id,
    m.impressions_march,
    m.clicks_march,
    m.ctr_march_pct,
    m.weighted_position_march,
    m.gsc_days_available,
    m.content_type,
    m.search_volume,
    m.word_count,
    a.impressions_april,
    a.clicks_april,
    a.ctr_april_pct,

    CASE
        WHEN m.weighted_position_march <= 3 THEN 'top_3'
        WHEN m.weighted_position_march <= 10 THEN 'positions_4_10'
        WHEN m.weighted_position_march <= 20 THEN 'positions_11_20'
        WHEN m.weighted_position_march <= 50 THEN 'positions_21_50'
        ELSE 'positions_51_plus'
    END AS march_position_tier

FROM march_dev m
INNER JOIN april_outcomes_scored a
    ON m.client_hash_id = a.client_hash_id
   AND m.content_hash_id = a.content_hash_id

WHERE m.impressions_march >= 300
  AND m.ctr_march_pct IS NOT NULL
  AND m.weighted_position_march IS NOT NULL
  AND a.impressions_april > 0
  AND a.ctr_april_pct IS NOT NULL
""")

print("Primary cohort: eligible from March; measurable April outcome")
display(con.execute("""
    SELECT
        COUNT(*) AS eligible_pairs,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(*) FILTER (
            WHERE impressions_april >= 300
        ) AS also_at_least_300_april_impressions,
        COUNT(*) FILTER (
            WHERE march_position_tier = 'positions_51_plus'
        ) AS positions_51_plus_pairs
    FROM march_april_cohort_v2
""").fetchdf())

print("March-eligible pairs without a measurable April outcome")
display(con.execute("""
    SELECT
        COUNT(*) AS march_eligible_pairs,
        COUNT(*) FILTER (
            WHERE a.content_hash_id IS NULL
        ) AS no_april_fact_record,
        COUNT(*) FILTER (
            WHERE a.content_hash_id IS NOT NULL
              AND COALESCE(a.impressions_april, 0) = 0
        ) AS april_record_without_impressions
    FROM march_dev m
    LEFT JOIN april_outcomes_scored a
        ON m.client_hash_id = a.client_hash_id
       AND m.content_hash_id = a.content_hash_id
    WHERE m.impressions_march >= 300
      AND m.ctr_march_pct IS NOT NULL
      AND m.weighted_position_march IS NOT NULL
""").fetchdf())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Primary cohort: eligible from March; measurable April outcome

,eligible_pairs,clients,also_at_least_300_april_impressions,positions_51_plus_pairs
0,74502,38,62985,1290

March-eligible pairs without a measurable April outcome

,march_eligible_pairs,no_april_fact_record,april_record_without_impressions
0,74666,0,164

In [31]:
import numpy as np
import pandas as pd

# Reproducible split of distinct clients, not individual page rows.
client_ids = con.execute("""
    SELECT DISTINCT client_hash_id
    FROM march_april_cohort_v2
    ORDER BY client_hash_id
""").fetchdf()["client_hash_id"].tolist()

rng = np.random.RandomState(42)
shuffled_clients = rng.permutation(client_ids)

n_test_clients = max(1, round(len(shuffled_clients) * 0.20))
test_clients = set(shuffled_clients[:n_test_clients])
train_clients = set(shuffled_clients[n_test_clients:])

split_df = pd.DataFrame({
    "client_hash_id": client_ids,
    "split": [
        "test" if cid in test_clients else "train"
        for cid in client_ids
    ]
})

con.register("client_split_df", split_df)

con.execute("""
CREATE OR REPLACE TABLE client_split AS
SELECT * FROM client_split_df
""")

con.execute("""
CREATE OR REPLACE TABLE model_cohort AS
SELECT c.*, s.split
FROM march_april_cohort_v2 c
JOIN client_split s USING (client_hash_id)
WHERE c.march_position_tier != 'positions_51_plus'
""")

print("Client-level split summary:")
display(con.execute("""
    SELECT
        split,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(*) AS page_pairs
    FROM model_cohort
    GROUP BY split
    ORDER BY split
""").fetchdf())

print("Position tiers by split:")
display(con.execute("""
    SELECT
        split,
        march_position_tier,
        COUNT(*) AS page_pairs
    FROM model_cohort
    GROUP BY split, march_position_tier
    ORDER BY split, march_position_tier
""").fetchdf())

Client-level split summary:

   split  clients  page_pairs
0   test        8       11338
1  train       29       61874

Position tiers by split:

   split march_position_tier  page_pairs
0   test     positions_11_20        2761
1   test     positions_21_50        2058
2   test      positions_4_10        5450
3   test               top_3        1069
4  train     positions_11_20       10826
5  train     positions_21_50       11040
6  train      positions_4_10       32273
7  train               top_3        7735

In [32]:
con.execute("""
CREATE OR REPLACE TABLE train_tier_reference AS
SELECT
    march_position_tier,
    COUNT(*) AS train_pairs,
    MEDIAN(ctr_april_pct) AS train_median_april_ctr_pct
FROM model_cohort
WHERE split = 'train'
GROUP BY march_position_tier
""")

print("Training-only April CTR reference:")
display(con.execute("""
    SELECT
        march_position_tier,
        train_pairs,
        ROUND(train_median_april_ctr_pct, 4)
            AS train_median_april_ctr_pct
    FROM train_tier_reference
    ORDER BY march_position_tier
""").fetchdf())

con.execute("""
CREATE OR REPLACE TABLE labeled_cohort AS
SELECT
    c.*,
    r.train_median_april_ctr_pct,

    CASE
        WHEN c.ctr_april_pct < r.train_median_april_ctr_pct
            THEN 1
        ELSE 0
    END AS below_reference_label,

    GREATEST(
        0.0,
        r.train_median_april_ctr_pct - c.ctr_april_pct
    ) AS opportunity_gap_pp

FROM model_cohort c
JOIN train_tier_reference r USING (march_position_tier)
""")

print("Label balance by split:")
display(con.execute("""
    SELECT
        split,
        COUNT(*) AS page_pairs,
        SUM(below_reference_label) AS positive_labels,
        ROUND(AVG(below_reference_label) * 100, 2)
            AS positive_label_pct,
        ROUND(AVG(opportunity_gap_pp), 4)
            AS mean_opportunity_gap_pp
    FROM labeled_cohort
    GROUP BY split
    ORDER BY split
""").fetchdf())

Training-only April CTR reference:

  march_position_tier  train_pairs  train_median_april_ctr_pct
0     positions_11_20        10826                      0.0920
1     positions_21_50        11040                      0.0471
2      positions_4_10        32273                      0.1524
3               top_3         7735                      0.1700

Label balance by split:

,split,page_pairs,positive_labels,positive_label_pct,mean_opportunity_gap_pp
0,test,11338,5841.0,51.52,0.0498
1,train,61874,30936.0,50.00,0.0478

In [33]:
con.execute("""
CREATE OR REPLACE TABLE train_march_tier_reference AS
SELECT
    march_position_tier,
    MEDIAN(ctr_march_pct) AS train_median_march_ctr_pct
FROM model_cohort
WHERE split = 'train'
GROUP BY march_position_tier
""")

con.execute("""
CREATE OR REPLACE TABLE ranked_cohort AS
SELECT
    c.*,
    r.train_median_march_ctr_pct,
    GREATEST(
        0.0,
        r.train_median_march_ctr_pct - c.ctr_march_pct
    ) AS baseline_opportunity_score
FROM labeled_cohort c
JOIN train_march_tier_reference r
    USING (march_position_tier)
""")

baseline_summary = con.execute("""
SELECT
    split,
    COUNT(*) AS page_pairs,
    ROUND(AVG(baseline_opportunity_score), 4)
        AS mean_baseline_score,
    ROUND(
        100.0 * AVG(
            CASE WHEN baseline_opportunity_score > 0 THEN 1.0 ELSE 0.0 END
        ),
        2
    ) AS pct_with_positive_baseline_score
FROM ranked_cohort
GROUP BY split
ORDER BY split
""").fetchdf()

display(baseline_summary)

   split  page_pairs  mean_baseline_score  pct_with_positive_baseline_score
0   test       11338               0.0440                             39.65
1  train       61874               0.0563                             50.00

In [35]:
con.execute("DESCRIBE ranked_cohort").fetchdf()

                   column_name column_type null   key default extra
0               client_hash_id     VARCHAR  YES  None    None  None
1              content_hash_id     VARCHAR  YES  None    None  None
2            impressions_march     HUGEINT  YES  None    None  None
3                 clicks_march     HUGEINT  YES  None    None  None
4                ctr_march_pct      DOUBLE  YES  None    None  None
5      weighted_position_march      DOUBLE  YES  None    None  None
6           gsc_days_available      BIGINT  YES  None    None  None
7                 content_type     VARCHAR  YES  None    None  None
8                search_volume      BIGINT  YES  None    None  None
9                   word_count      BIGINT  YES  None    None  None
10           impressions_april     HUGEINT  YES  None    None  None
11                clicks_april     HUGEINT  YES  None    None  None
12               ctr_april_pct      DOUBLE  YES  None    None  None
13         march_position_tier     VARCHAR  YES  None    None  None
14                       split     VARCHAR  YES  None    None  None
15  train_median_april_ctr_pct      DOUBLE  YES  None    None  None
16       below_reference_label     INTEGER  YES  None    None  None
17          opportunity_gap_pp      DOUBLE  YES  None    None  None
18  train_median_march_ctr_pct      DOUBLE  YES  None    None  None
19  baseline_opportunity_score      DOUBLE  YES  None    None  None

In [36]:
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

model_df = con.execute(f"""
SELECT
    r.client_hash_id,
    r.content_hash_id,
    r.split,
    r.march_position_tier,
    r.impressions_march,
    r.ctr_march_pct,
    r.weighted_position_march,
    r.gsc_days_available,
    r.search_volume,
    r.word_count,
    r.content_type,
    c.main_intent,
    r.below_reference_label,
    r.opportunity_gap_pp,
    r.baseline_opportunity_score
FROM ranked_cohort r
LEFT JOIN read_parquet('{content_path}') c
    ON r.client_hash_id = c.client_hash_id
   AND r.content_hash_id = c.content_hash_id
""").fetchdf()

numeric_features = [
    "log_impressions_march",
    "ctr_march_pct",
    "weighted_position_march",
    "gsc_days_available",
    "search_volume",
    "word_count",
]

categorical_features = [
    "march_position_tier",
    "content_type",
    "main_intent",
]

model_df["log_impressions_march"] = np.log1p(
    model_df["impressions_march"].clip(lower=0)
)

feature_columns = numeric_features + categorical_features

train_df = model_df[model_df["split"] == "train"].copy()
test_df = model_df[model_df["split"] == "test"].copy()

X_train = train_df[feature_columns]
y_train = train_df["below_reference_label"].astype(int)

X_test = test_df[feature_columns]
y_test = test_df["below_reference_label"].astype(int)

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore")),
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features),
])

model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=200,
        min_samples_leaf=10,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )),
])

model.fit(X_train, y_train)
test_df["model_probability"] = model.predict_proba(X_test)[:, 1]

print("Training rows:", len(train_df))
print("Test rows:", len(test_df))
print("Features:", feature_columns)
print("Test positive-label rate:", round(100 * y_test.mean(), 2), "%")
print("Model trained successfully.")

Training rows: 61874
Test rows: 11338
Features: ['log_impressions_march', 'ctr_march_pct', 'weighted_position_march', 'gsc_days_available', 'search_volume', 'word_count', 'march_position_tier', 'content_type', 'main_intent']
Test positive-label rate: 51.52 %
Model trained successfully.

In [37]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score, average_precision_score

# Use the same held-out pages and the same target for both rankings.
evaluation_df = test_df[
    [
        "below_reference_label",
        "opportunity_gap_pp",
        "baseline_opportunity_score",
        "model_probability",
    ]
].copy()

evaluation_df["below_reference_label"] = (
    evaluation_df["below_reference_label"].astype(int)
)

base_rate = evaluation_df["below_reference_label"].mean()
k = max(1, int(np.ceil(len(evaluation_df) * 0.10)))

def evaluate_ranking(df, score_column, ranking_name):
    ranked = df.sort_values(score_column, ascending=False)
    top_k = ranked.head(k)

    precision_at_k = top_k["below_reference_label"].mean()
    recall_at_k = (
        top_k["below_reference_label"].sum()
        / df["below_reference_label"].sum()
    )

    return {
        "ranking": ranking_name,
        "test_pages": len(df),
        "k_top_10pct": k,
        "base_rate_pct": round(100 * base_rate, 2),
        "precision_at_k_pct": round(100 * precision_at_k, 2),
        "lift_vs_base_rate": round(
            precision_at_k / base_rate, 3
        ) if base_rate > 0 else np.nan,
        "recall_at_k_pct": round(100 * recall_at_k, 2),
        "mean_gap_top_k_pp": round(
            top_k["opportunity_gap_pp"].mean(), 4
        ),
    }

ranking_results = pd.DataFrame([
    evaluate_ranking(
        evaluation_df,
        "baseline_opportunity_score",
        "March CTR baseline",
    ),
    evaluate_ranking(
        evaluation_df,
        "model_probability",
        "Random Forest",
    ),
])

display(ranking_results)

print("ML ROC-AUC:", round(
    roc_auc_score(
        evaluation_df["below_reference_label"],
        evaluation_df["model_probability"],
    ), 4
))

print("ML average precision:", round(
    average_precision_score(
        evaluation_df["below_reference_label"],
        evaluation_df["model_probability"],
    ), 4
))

,ranking,test_pages,k_top_10pct,base_rate_pct,precision_at_k_pct,lift_vs_base_rate,recall_at_k_pct,mean_gap_top_k_pp
0,March CTR baseline,11338,1134,51.52,80.69,1.566,15.67,0.1195
1,Random Forest,11338,1134,51.52,85.19,1.654,16.54,0.0887

ML ROC-AUC: 0.8158
ML average precision: 0.7903

In [38]:
import pandas as pd

fitted_preprocessor = model.named_steps["preprocessor"]
fitted_classifier = model.named_steps["classifier"]

transformed_feature_names = fitted_preprocessor.get_feature_names_out()

importance_df = pd.DataFrame({
    "feature": transformed_feature_names,
    "importance": fitted_classifier.feature_importances_,
}).sort_values("importance", ascending=False)

display(
    importance_df.head(15).assign(
        importance=lambda df: df["importance"].round(4)
    )
)

print(
    "Total feature importance:",
    round(importance_df["importance"].sum(), 4)
)

                                             feature  importance
1                             numeric__ctr_march_pct      0.5746
0                     numeric__log_impressions_march      0.1567
2                   numeric__weighted_position_march      0.0957
5                                numeric__word_count      0.0742
4                             numeric__search_volume      0.0331
3                        numeric__gsc_days_available      0.0238
7   categorical__march_position_tier_positions_21_50      0.0101
8    categorical__march_position_tier_positions_4_10      0.0067
14            categorical__main_intent_informational      0.0056
16            categorical__main_intent_transactional      0.0049
6   categorical__march_position_tier_positions_11_20      0.0044
13               categorical__main_intent_commercial      0.0036
9             categorical__march_position_tier_top_3      0.0036
10      categorical__content_type_comparison article      0.0017
12         categorical__content_type_keyword article      0.0007

Total feature importance: 1.0

In [39]:
import pandas as pd

fitted_preprocessor = model.named_steps["preprocessor"]
fitted_classifier = model.named_steps["classifier"]

transformed_feature_names = fitted_preprocessor.get_feature_names_out()

importance_df = pd.DataFrame({
    "feature": transformed_feature_names,
    "importance": fitted_classifier.feature_importances_,
}).sort_values("importance", ascending=False)

display(
    importance_df.head(15).assign(
        importance=lambda df: df["importance"].round(4)
    )
)

print(
    "Total feature importance:",
    round(importance_df["importance"].sum(), 4)
)

                                             feature  importance
1                             numeric__ctr_march_pct      0.5746
0                     numeric__log_impressions_march      0.1567
2                   numeric__weighted_position_march      0.0957
5                                numeric__word_count      0.0742
4                             numeric__search_volume      0.0331
3                        numeric__gsc_days_available      0.0238
7   categorical__march_position_tier_positions_21_50      0.0101
8    categorical__march_position_tier_positions_4_10      0.0067
14            categorical__main_intent_informational      0.0056
16            categorical__main_intent_transactional      0.0049
6   categorical__march_position_tier_positions_11_20      0.0044
13               categorical__main_intent_commercial      0.0036
9             categorical__march_position_tier_top_3      0.0036
10      categorical__content_type_comparison article      0.0017
12         categorical__content_type_keyword article      0.0007

Total feature importance: 1.0

In [40]:
import json
from pathlib import Path

development_record = {
    "lane": "CTR / Engagement Opportunity Scoring",
    "development_feature_month": "2026-03",
    "development_outcome_month": "2026-04",
    "split_unit": "client_hash_id",
    "split_seed": 42,
    "train_clients": 29,
    "test_clients": 8,
    "train_page_pairs": 61874,
    "test_page_pairs": 11338,
    "position_tiers_in_primary_model": [
        "top_3",
        "positions_4_10",
        "positions_11_20",
        "positions_21_50"
    ],
    "excluded_tier": "positions_51_plus",
    "model": "RandomForestClassifier",
    "model_parameters": {
        "n_estimators": 200,
        "min_samples_leaf": 10,
        "class_weight": "balanced",
        "random_state": 42
    },
    "feature_columns": feature_columns,
    "target": (
        "April CTR below the training-client April median "
        "for the March position tier"
    ),
    "primary_ranking_metric": "Precision@10%",
    "baseline": (
        "Positive shortfall between March CTR and the "
        "training-client March median for the March position tier"
    ),
    "test_metrics": {
        "base_rate_pct": 51.52,
        "baseline_precision_at_10_pct": 80.69,
        "model_precision_at_10_pct": 85.19,
        "baseline_lift": 1.566,
        "model_lift": 1.654,
        "baseline_recall_at_10_pct": 15.67,
        "model_recall_at_10_pct": 16.54,
        "model_roc_auc": 0.8158,
        "model_average_precision": 0.7903
    }
}

record_path = Path(
    "/content/jsk-flyrank-ml-internship/work/"
    "notebooks/development_record.json"
)
record_path.parent.mkdir(parents=True, exist_ok=True)
record_path.write_text(
    json.dumps(development_record, indent=2)
)

print("Development choices recorded at:", record_path)
print("June remains unused.")

Development choices recorded at: /content/jsk-flyrank-ml-internship/work/notebooks/development_record.json
June remains unused.

In [41]:
may_path = (
    "hf://datasets/FlyRank/internship-warehouse/"
    "fact_content_daily_performance/month=2026-05/data_0.parquet"
)

may_schema = con.execute(
    f"DESCRIBE SELECT * FROM read_parquet('{may_path}')"
).fetchdf()

display(may_schema)

may_quality = con.execute(f"""
SELECT
    MIN(report_date) AS first_date,
    MAX(report_date) AS last_date,
    COUNT(*) AS rows,
    COUNT(DISTINCT client_hash_id) AS clients,
    COUNT(DISTINCT content_hash_id) AS content_ids,
    COUNT(*) FILTER (
        WHERE gsc_data_available IS TRUE
    ) AS rows_with_gsc,
    COUNT(*) FILTER (
        WHERE ga4_data_available IS TRUE
    ) AS rows_with_ga4,
    COUNT(*) FILTER (
        WHERE gsc_data_available IS TRUE
          AND gsc_avg_position IS NOT NULL
    ) AS rows_with_position
FROM read_parquet('{may_path}')
""").fetchdf()

display(may_quality)

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,first_date,last_date,rows,clients,content_ids,rows_with_gsc,rows_with_ga4,rows_with_position
0,2026-05-01,2026-05-31,11687376,66,389153,4373422,740601,4373422

In [42]:
con.execute(f"""
CREATE OR REPLACE TABLE may_features AS
WITH monthly AS (
    SELECT
        client_hash_id,
        content_hash_id,

        COUNT(DISTINCT report_date)
            FILTER (WHERE gsc_data_available IS TRUE)
            AS gsc_days_available,

        SUM(gsc_impressions)
            FILTER (WHERE gsc_data_available IS TRUE)
            AS impressions_may,

        SUM(gsc_clicks)
            FILTER (WHERE gsc_data_available IS TRUE)
            AS clicks_may,

        SUM(gsc_sum_position)
            FILTER (
                WHERE gsc_data_available IS TRUE
                  AND gsc_avg_position IS NOT NULL
            )
            AS position_sum_may,

        SUM(gsc_impressions)
            FILTER (
                WHERE gsc_data_available IS TRUE
                  AND gsc_avg_position IS NOT NULL
            )
            AS impressions_with_position_may

    FROM read_parquet('{may_path}')
    WHERE report_date >= DATE '2026-05-01'
      AND report_date < DATE '2026-06-01'
    GROUP BY client_hash_id, content_hash_id
)
SELECT
    m.*,

    100.0 * clicks_may
        / NULLIF(impressions_may, 0)
        AS ctr_may_pct,

    position_sum_may::DOUBLE
        / NULLIF(impressions_with_position_may, 0)
        AS weighted_position_may,

    c.content_type,
    c.search_volume,
    c.word_count,
    c.main_intent,

    CASE
        WHEN position_sum_may IS NULL
          OR impressions_with_position_may = 0
            THEN NULL
        WHEN position_sum_may::DOUBLE
             / NULLIF(impressions_with_position_may, 0) <= 3
            THEN 'top_3'
        WHEN position_sum_may::DOUBLE
             / NULLIF(impressions_with_position_may, 0) <= 10
            THEN 'positions_4_10'
        WHEN position_sum_may::DOUBLE
             / NULLIF(impressions_with_position_may, 0) <= 20
            THEN 'positions_11_20'
        WHEN position_sum_may::DOUBLE
             / NULLIF(impressions_with_position_may, 0) <= 50
            THEN 'positions_21_50'
        ELSE 'positions_51_plus'
    END AS may_position_tier

FROM monthly m
LEFT JOIN read_parquet('{content_path}') c
    ON m.client_hash_id = c.client_hash_id
   AND m.content_hash_id = c.content_hash_id
""")

may_summary = con.execute("""
SELECT
    COUNT(*) AS page_pairs,
    COUNT(DISTINCT client_hash_id) AS clients,
    COUNT(*) FILTER (WHERE impressions_may > 0)
        AS pairs_with_impressions,
    COUNT(*) FILTER (WHERE ctr_may_pct IS NOT NULL)
        AS pairs_with_defined_ctr,
    COUNT(*) FILTER (WHERE weighted_position_may IS NOT NULL)
        AS pairs_with_position,
    COUNT(*) FILTER (WHERE content_type IS NULL)
        AS missing_content_type,
    COUNT(*) FILTER (WHERE main_intent IS NULL)
        AS missing_main_intent
FROM may_features
""").fetchdf()

display(may_summary)

display(con.execute("""
SELECT
    may_position_tier,
    COUNT(*) AS page_pairs
FROM may_features
WHERE impressions_may > 0
GROUP BY may_position_tier
ORDER BY may_position_tier
""").fetchdf())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,page_pairs,clients,pairs_with_impressions,pairs_with_defined_ctr,pairs_with_position,missing_content_type,missing_main_intent
0,389153,66,237910,237910,237910,0,65153

   may_position_tier  page_pairs
0    positions_11_20       52976
1    positions_21_50       60154
2     positions_4_10       69415
3  positions_51_plus       19626
4              top_3       35739

In [43]:
may_summary = con.execute("""
SELECT
    COUNT(*) AS page_pairs,
    COUNT(DISTINCT client_hash_id) AS clients,
    COUNT(*) FILTER (WHERE impressions_may > 0)
        AS pairs_with_impressions,
    COUNT(*) FILTER (WHERE ctr_may_pct IS NOT NULL)
        AS pairs_with_defined_ctr,
    COUNT(*) FILTER (WHERE weighted_position_may IS NOT NULL)
        AS pairs_with_position,
    COUNT(*) FILTER (WHERE content_type IS NULL)
        AS missing_content_type,
    COUNT(*) FILTER (WHERE main_intent IS NULL)
        AS missing_main_intent
FROM may_features
""").fetchone()

for name, value in zip(
    [
        "page_pairs",
        "clients",
        "pairs_with_impressions",
        "pairs_with_defined_ctr",
        "pairs_with_position",
        "missing_content_type",
        "missing_main_intent",
    ],
    may_summary,
):
    print(f"{name}: {value}")

page_pairs: 389153
clients: 66
pairs_with_impressions: 237910
pairs_with_defined_ctr: 237910
pairs_with_position: 237910
missing_content_type: 0
missing_main_intent: 65153

In [44]:
# Restrict to rows with observable May CTR and position.
may_scoring_df = con.execute("""
SELECT *
FROM may_features
WHERE ctr_may_pct IS NOT NULL
  AND weighted_position_may IS NOT NULL
""").fetchdf()

# Match the training feature names to the May snapshot.
may_scoring_df["log_impressions_march"] = np.log1p(
    may_scoring_df["impressions_may"].clip(lower=0)
)

may_scoring_df["ctr_march_pct"] = may_scoring_df["ctr_may_pct"]
may_scoring_df["weighted_position_march"] = (
    may_scoring_df["weighted_position_may"]
)
may_scoring_df["march_position_tier"] = (
    may_scoring_df["may_position_tier"]
)

may_X = may_scoring_df[feature_columns]

may_scoring_df["model_probability"] = model.predict_proba(may_X)[:, 1]

# A comparable baseline using frozen March training medians.
may_baseline_refs = con.execute("""
SELECT
    march_position_tier,
    train_median_march_ctr_pct
FROM train_march_tier_reference
""").fetchdf()

may_scoring_df = may_scoring_df.merge(
    may_baseline_refs,
    on="march_position_tier",
    how="left",
    validate="many_to_one",
)

may_scoring_df["baseline_opportunity_score"] = np.maximum(
    0.0,
    may_scoring_df["train_median_march_ctr_pct"]
    - may_scoring_df["ctr_may_pct"],
)

print("May rows scored:", len(may_scoring_df))
print("Clients scored:", may_scoring_df["client_hash_id"].nunique())
print("Missing model probabilities:",
      may_scoring_df["model_probability"].isna().sum())
print("Missing baseline scores:",
      may_scoring_df["baseline_opportunity_score"].isna().sum())

display(
    may_scoring_df[
        [
            "may_position_tier",
            "model_probability",
            "baseline_opportunity_score",
        ]
    ]
    .groupby("may_position_tier")
    .agg(
        page_pairs=("model_probability", "size"),
        mean_model_probability=("model_probability", "mean"),
        mean_baseline_score=("baseline_opportunity_score", "mean"),
    )
    .round(4)
)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

May rows scored: 237910
Clients scored: 56
Missing model probabilities: 0
Missing baseline scores: 19626

                   page_pairs  mean_model_probability  mean_baseline_score
may_position_tier
positions_11_20         52976                  0.5634               0.0885
positions_21_50         60154                  0.6457               0.0463
positions_4_10          69415                  0.5172               0.1074
positions_51_plus       19626                  0.7386                  NaN
top_3                   35739                  0.7375               0.2104

In [45]:
# Attach the frozen client split to May's scored rows.
may_scoring_df = may_scoring_df.merge(
    con.execute("SELECT client_hash_id, split FROM client_split").fetchdf(),
    on="client_hash_id",
    how="inner",
    validate="many_to_one",
)

# Restrict the final evaluation to held-out clients and the four
# position tiers used in development.
final_may_cohort = may_scoring_df[
    (may_scoring_df["split"] == "test")
    & (may_scoring_df["may_position_tier"] != "positions_51_plus")
].copy()

cohort_summary = (
    final_may_cohort
    .groupby("may_position_tier")
    .agg(
        page_pairs=("content_hash_id", "size"),
        clients=("client_hash_id", "nunique"),
    )
    .reset_index()
)

print("Held-out clients represented:",
      final_may_cohort["client_hash_id"].nunique())
print("May feature rows in final cohort:", len(final_may_cohort))
print("Missing model probabilities:",
      final_may_cohort["model_probability"].isna().sum())
print("Missing baseline scores:",
      final_may_cohort["baseline_opportunity_score"].isna().sum())

display(cohort_summary)

Held-out clients represented: 8
May feature rows in final cohort: 23402
Missing model probabilities: 0
Missing baseline scores: 0

  may_position_tier  page_pairs  clients
0   positions_11_20        7478        8
1   positions_21_50        8083        8
2    positions_4_10        7465        8
3             top_3         376        8

In [46]:
from sklearn.metrics import roc_auc_score, average_precision_score
import numpy as np
import pandas as pd

# June is accessed only now, after the development protocol is frozen.
june_path = (
    "hf://datasets/FlyRank/internship-warehouse/"
    "fact_content_daily_performance/month=2026-06/data_0.parquet"
)

# Aggregate June outcomes, respecting GSC availability.
con.execute(f"""
CREATE OR REPLACE TABLE june_outcomes AS
SELECT
    client_hash_id,
    content_hash_id,
    SUM(gsc_impressions)
        FILTER (WHERE gsc_data_available IS TRUE) AS impressions_june,
    SUM(gsc_clicks)
        FILTER (WHERE gsc_data_available IS TRUE) AS clicks_june
FROM read_parquet('{june_path}')
WHERE report_date >= DATE '2026-06-01'
  AND report_date < DATE '2026-07-01'
GROUP BY client_hash_id, content_hash_id
""")

con.execute("""
CREATE OR REPLACE TABLE june_outcomes_scored AS
SELECT
    *,
    100.0 * clicks_june / NULLIF(impressions_june, 0)
        AS ctr_june_pct
FROM june_outcomes
""")

june_outcome_summary = con.execute("""
SELECT
    COUNT(*) AS june_page_pairs,
    COUNT(DISTINCT client_hash_id) AS june_clients,
    COUNT(*) FILTER (WHERE impressions_june > 0)
        AS pairs_with_june_impressions
FROM june_outcomes_scored
""").fetchdf()

display(june_outcome_summary)

# Join the June outcomes to the previously frozen May scoring cohort.
june_df = con.execute("""
SELECT
    m.client_hash_id,
    m.content_hash_id,
    m.may_position_tier,
    m.model_probability,
    m.baseline_opportunity_score,
    j.impressions_june,
    j.clicks_june,
    j.ctr_june_pct
FROM final_may_cohort m
JOIN june_outcomes_scored j
  ON m.client_hash_id = j.client_hash_id
 AND m.content_hash_id = j.content_hash_id
WHERE j.impressions_june > 0
  AND j.ctr_june_pct IS NOT NULL
""").fetchdf()

# Apply the frozen April reference medians; do not calculate new June medians.
june_df = june_df.merge(
    con.execute("""
        SELECT
            march_position_tier AS may_position_tier,
            train_median_april_ctr_pct
        FROM train_tier_reference
    """).fetchdf(),
    on="may_position_tier",
    how="left",
    validate="many_to_one",
)

if june_df["train_median_april_ctr_pct"].isna().any():
    raise ValueError("Missing frozen reference threshold for a position tier.")

june_df["june_below_reference_label"] = (
    june_df["ctr_june_pct"] < june_df["train_median_april_ctr_pct"]
).astype(int)

june_df["june_opportunity_gap_pp"] = np.maximum(
    0.0,
    june_df["train_median_april_ctr_pct"] - june_df["ctr_june_pct"],
)

base_rate = june_df["june_below_reference_label"].mean()
k = max(1, int(np.ceil(len(june_df) * 0.10)))

def evaluate_june_ranking(df, score_column, ranking_name):
    ranked = df.sort_values(score_column, ascending=False)
    top_k = ranked.head(k)

    precision = top_k["june_below_reference_label"].mean()
    total_positives = df["june_below_reference_label"].sum()
    recall = (
        top_k["june_below_reference_label"].sum() / total_positives
        if total_positives else np.nan
    )

    return {
        "ranking": ranking_name,
        "evaluated_pairs": len(df),
        "top_k": k,
        "base_rate_pct": round(100 * base_rate, 2),
        "precision_at_10_pct": round(100 * precision, 2),
        "lift_vs_base_rate": round(precision / base_rate, 3)
            if base_rate else np.nan,
        "recall_at_10_pct": round(100 * recall, 2)
            if not np.isnan(recall) else np.nan,
        "mean_june_gap_top_k_pp": round(
            top_k["june_opportunity_gap_pp"].mean(), 4
        ),
    }

june_ranking_results = pd.DataFrame([
    evaluate_june_ranking(
        june_df, "baseline_opportunity_score", "May CTR baseline"
    ),
    evaluate_june_ranking(
        june_df, "model_probability", "Frozen Random Forest"
    ),
])

print("May eligible rows:", len(final_may_cohort))
print("Rows with measurable June CTR:", len(june_df))
print("Held-out clients evaluated:", june_df["client_hash_id"].nunique())
print("June positive-label rate:", round(100 * base_rate, 2), "%")

display(june_ranking_results)

if june_df["june_below_reference_label"].nunique() == 2:
    print(
        "June ROC-AUC:",
        round(roc_auc_score(
            june_df["june_below_reference_label"],
            june_df["model_probability"],
        ), 4),
    )
    print(
        "June average precision:",
        round(average_precision_score(
            june_df["june_below_reference_label"],
            june_df["model_probability"],
        ), 4),
    )
else:
    print("June ROC-AUC and average precision are undefined: only one label class.")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   june_page_pairs  june_clients  pairs_with_june_impressions
0           409205            65                       208636

May eligible rows: 23402
Rows with measurable June CTR: 21548
Held-out clients evaluated: 8
June positive-label rate: 55.35 %

,ranking,evaluated_pairs,top_k,base_rate_pct,precision_at_10_pct,lift_vs_base_rate,recall_at_10_pct,mean_june_gap_top_k_pp
0,May CTR baseline,21548,2155,55.35,80.65,1.457,14.57,0.1236
1,Frozen Random Forest,21548,2155,55.35,82.55,1.491,14.92,0.0582

June ROC-AUC: 0.7908
June average precision: 0.7784

In [47]:
tier_results = []

for tier, group in june_df.groupby("may_position_tier"):
    n = len(group)
    k_tier = max(1, int(np.ceil(n * 0.10)))
    tier_base_rate = group["june_below_reference_label"].mean()

    for score_column, ranking_name in [
        ("baseline_opportunity_score", "May CTR baseline"),
        ("model_probability", "Frozen Random Forest"),
    ]:
        top = group.sort_values(
            score_column, ascending=False
        ).head(k_tier)

        precision = top["june_below_reference_label"].mean()
        positive_count = group["june_below_reference_label"].sum()

        tier_results.append({
            "may_position_tier": tier,
            "ranking": ranking_name,
            "page_pairs": n,
            "top_10pct_count": k_tier,
            "base_rate_pct": round(100 * tier_base_rate, 2),
            "precision_at_10_pct": round(100 * precision, 2),
            "lift_vs_tier_base_rate": round(
                precision / tier_base_rate, 3
            ) if tier_base_rate > 0 else np.nan,
            "recall_at_10_pct": round(
                100 * top["june_below_reference_label"].sum()
                / positive_count, 2
            ) if positive_count > 0 else np.nan,
        })

tier_results_df = pd.DataFrame(tier_results)
display(tier_results_df.sort_values(
    ["may_position_tier", "ranking"]
).reset_index(drop=True))

,may_position_tier,ranking,page_pairs,top_10pct_count,base_rate_pct,precision_at_10_pct,lift_vs_tier_base_rate,recall_at_10_pct
0,positions_11_20,Frozen Random Forest,7022,703,51.45,76.53,1.487,14.89
1,positions_11_20,May CTR baseline,7022,703,51.45,76.24,1.482,14.84
2,positions_21_50,Frozen Random Forest,7231,724,71.15,86.88,1.221,12.23
3,positions_21_50,May CTR baseline,7231,724,71.15,86.05,1.209,12.11
4,positions_4_10,Frozen Random Forest,7040,704,42.43,74.29,1.751,17.51
5,positions_4_10,May CTR baseline,7040,704,42.43,81.53,1.922,19.22
6,top_3,Frozen Random Forest,255,26,71.37,80.77,1.132,11.54
7,top_3,May CTR baseline,255,26,71.37,100.00,1.401,14.29

In [48]:
from pathlib import Path

repo = Path("/content/jsk-flyrank-ml-internship")
work = repo / "work"

print("Work directory:")
for path in sorted(work.iterdir()):
    print(("DIR  " if path.is_dir() else "FILE "), path.name)

print("\nExisting submission directory:")
submission = repo / "submission"
if submission.exists():
    for path in sorted(submission.iterdir()):
        print(("DIR  " if path.is_dir() else "FILE "), path.name)
else:
    print("submission/ does not exist yet")

Work directory:
FILE  README.md
FILE  capstone_report_template.md
DIR   notebooks

Existing submission directory:
FILE  README.md
FILE  paper_url.txt

In [49]:
import json
from pathlib import Path

repo = Path("/content/jsk-flyrank-ml-internship")
record_path = repo / "work" / "notebooks" / "development_record.json"

with record_path.open("r") as f:
    record = json.load(f)

# June overall results: aggregate metrics only.
record["final_test"] = {
    "feature_month": "2026-05",
    "outcome_month": "2026-06",
    "held_out_clients": int(june_df["client_hash_id"].nunique()),
    "may_eligible_rows": int(len(final_may_cohort)),
    "evaluated_pairs": int(len(june_df)),
    "pairs_without_measurable_june_ctr": int(
        len(final_may_cohort) - len(june_df)
    ),
    "positive_label_rate_pct": round(
        100 * june_df["june_below_reference_label"].mean(), 2
    ),
    "baseline_precision_at_10_pct": 80.65,
    "model_precision_at_10_pct": 82.55,
    "baseline_lift": 1.457,
    "model_lift": 1.491,
    "baseline_recall_at_10_pct": 14.57,
    "model_recall_at_10_pct": 14.92,
    "baseline_mean_gap_top_10_pp": 0.1236,
    "model_mean_gap_top_10_pp": 0.0582,
    "model_roc_auc": 0.7908,
    "model_average_precision": 0.7784,
}

# Aggregate tier results only; no individual records.
record["final_test"]["tier_results"] = (
    tier_results_df[
        [
            "may_position_tier",
            "ranking",
            "page_pairs",
            "top_10pct_count",
            "base_rate_pct",
            "precision_at_10_pct",
            "lift_vs_tier_base_rate",
            "recall_at_10_pct",
        ]
    ]
    .round(4)
    .to_dict(orient="records")
)

record["limitations"] = [
    "Observational decision-support analysis; no causal claims.",
    "June evaluation includes only eligible May rows with measurable June CTR.",
    "June outcomes were not used to train or tune the model.",
    "The model has a modest overall Precision@10% advantage over the baseline.",
    "Tier-level results vary; the baseline performs better in positions 4-10 and top_3.",
    "The top_3 tier has a small evaluated sample.",
    "Positions 51+ were excluded from the primary comparison.",
]

record_path.write_text(json.dumps(record, indent=2))

print("Updated aggregate metrics artifact:", record_path)
print("Contains individual client IDs:", False)
print("Contains individual content IDs:", False)

Updated aggregate metrics artifact: /content/jsk-flyrank-ml-internship/work/notebooks/development_record.json
Contains individual client IDs: False
Contains individual content IDs: False

In [50]:
import json
from pathlib import Path

notebook_path = Path(
    "/content/jsk-flyrank-ml-internship/work/notebooks/capstone.ipynb"
)

with notebook_path.open("r", encoding="utf-8") as f:
    notebook = json.load(f)

for i, cell in enumerate(notebook["cells"]):
    source = "".join(cell.get("source", []))
    first_line = source.strip().splitlines()[0] if source.strip() else "(empty cell)"
    print(f"{i:02d} | {cell['cell_type']} | {first_line[:180]}")

00 | markdown | # Capstone — mirrors your deployed research paper
01 | markdown | ## 1. Question
02 | code | (empty cell)
03 | markdown | ## 2. Data
04 | code | (empty cell)
05 | markdown | ## 3. Methodology
06 | code | (empty cell)
07 | markdown | ## 4. Results (vs baseline)
08 | code | (empty cell)
09 | markdown | ## 5. Limitations
10 | code | (empty cell)
11 | markdown | ## 6. Ranked recommendations
12 | code | (empty cell)
13 | markdown | ## 7. Artifacts the paper embeds
14 | code | (empty cell)
15 | markdown | ## Self-check